### ISSUE TITLE
ParameterModule cause summary bug

### ISSUE THREAD

**Issue by lgvaz** [fastai/fastai2#10]
If we call `learn.summary()` on a model that has a `ParameterModule` the following error is raised:
```python
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-39-bc39e9e85f86> in <module>
----> 1 learn.summary()

~/forks/fastai2/fastai2/callback/hook.py in summary(self)
    170     res += "=" * n + "\n"
    171     ps,trn_ps = 0,0
--> 172     for typ,np,trn,sz in infos:
    173         if sz is None: continue
    174         ps += np

TypeError: cannot unpack non-iterable NoneType object
```

A very simple example is:
```python
m = ResBlock(1, 3, 32, sa=True)
learn = Learner(dbch, m)
learn.summary()
```
Where `SimpleSelfAttention` uses a `nn.Parameter` (`self.gamma`).

My first intuition was to go to `layer_info` and do:
```python
layers = [m for m in flatten_model(learn.model) if not isinstance(m, ParameterModule)]
```
But that is wrong, because we do want the parameter to show in the summary.

In reality I don't understand exactly why this error is thrown.

**Comment by sgugger** [comment]
I'll look into it on Monday, but don't expect the summary to work on any model since it has only been tested/used on regular CNNs.

**Comment by sgugger** [comment]
This is a quick fix to make the command work. The parameters wrapped in `ParameterModule` don't get counted however, as the hooks on them isn't called. There is a bit more we could do to add them to the summary (at least in the number of params and know if it's frozen or not).

**Comment by lgvaz** [comment]
Can you try to briefly explain why this error happens in the first place? `ParameterModule` is just a normal pytorch module, I don't understand why this happens...

**Comment by sgugger** [comment]
It's an artificial module in the sense that it's not called by the forward pass of the model. But if we don't add this, we lose some parameters (like the gamma in a self attention layer) in our optimizers (the self attention is the reason this ParameterModule was created).

But since they are not directly called (it's the self attention layer that is called, not the ParameterModule thingy) the function `layer_info` returns None for this module.
