### ISSUE TITLE
Flip with TensorPoint causes a bug

### ISSUE THREAD

**Issue by lgvaz** [fastai/fastai2#100]
There is something wrong with `Flip()` together with `TensorPoint`.

If I use no transforms the model trains correctly (not perfect but getting there):
![image](https://user-images.githubusercontent.com/16520544/74541398-4b5aa180-4f20-11ea-8164-e957fc71f589.png)

If I use all `aug_transforms(do_flip=False)` the model trains correctly:
![image](https://user-images.githubusercontent.com/16520544/74541441-5dd4db00-4f20-11ea-833d-9acc65ef289d.png)

But if `Flip()` is involved the model just fails, no matter how much you train it's always stuck with all the points vertically positioned in the middle of the cat head
![image](https://user-images.githubusercontent.com/16520544/74541456-63cabc00-4f20-11ea-869f-57b9332cc5a0.png)

I tried debugging the `Flip` function but it's seems to be working correctly, I flipped a cat image and the point were flipped accordingly. It's clear that `Flip` is causing this, but I cannot find why.

**Comment by sgugger** [comment]
If Flip works normally when looking at pictures, there is nothing we can do to fix with something that vague. Please keep debugging on the forum and reopen the issue when you have a clear reproducer of something going wrong, but there is nothing we can do without something more substantial.
