### ISSUE TITLE
SaveModelCallback to save n-best models

### ISSUE THREAD

**Issue by kamil-kaczmarek** [fastai/fastai2#104]
Hey,

Together with @jakubczakon we have an idea that [SaveModelCallback](https://github.com/fastai/fastai2/blob/master/fastai2/callback/tracker.py#L72) should allow users to save *n best* models weights.

It would be something between keeping only the best one and saving model weights after each epoch.

Use case is that I want to keep few best models that I obtain during training. Later I can use them for various tasks like averaging preds.

I can contribute this :slightly_smiling_face:

What do you think @sgugger ?

**Comment by sgugger** [comment]
If it's not too long to add to the existing SaveModelCallback, go for it. Otherwise it should go in a new callback.

**Comment by kamil-kaczmarek** [comment]
Nice,
I'll submit PR once ready to further discuss it.

**Comment by sgugger** [comment]
Closing the issue as we keep track of feature development on the [forum](https://forums.fast.ai/) usually (please don't hesitate to open a new topic to discuss this/ask for help) and leave the issues for standing bugs.

**Comment by kamil-kaczmarek** [comment]
Ok @sgugger, I'm still working on this one.
Under which category and topic should I ask questions regarding the development of the fastai2?

Thanks

**Comment by sgugger** [comment]
Just create any topic in the [fastai v2 category](https://forums.fast.ai/c/fastai-users/fastai-v2/).
