### ISSUE TITLE
Why does DynamicUnet have a BatchNorm layer at the end?

### ISSUE THREAD

**Issue by antorsae** [fastai/fastai2#107]
I'm instantiating a:

`learn=unet_learner(dls,models.resnet34,n_in=3*h.seq_len,n_out=3,normalize=False,loss_func=MSELossFlat(),config={'y_range':(0,1), 'blur_final' : False})`

and at the end:

```_______________________________________________________________
ReLU                 32 x 102 x 224 x 22  0          False     
________________________________________________________________
Conv2d               32 x 3 x 224 x 224   306        True      
________________________________________________________________
BatchNorm2d          32 x 3 x 224 x 224   6          True      
________________________________________________________________
SigmoidRange         32 x 3 x 224 x 224   0          False     
________________________________________________________________
```

Doesn't the BatchNorm2d right before the SigmoidRange force mean to 0? Is there a configurable way to remove the last `BatchNorm2d` ?

**Comment by sgugger** [comment]
All convs come as blocks of Conv + BatchNorm, as is the standard in all modern CNNs. There is no configurable way to remove it no. You're free to copy and paste the code for the model and change that last `ConvLayer`. Let us know if it changes anything, but I'm unsure it will.

**Comment by antorsae** [comment]
It does. That last BN forcing mean to 0 and std to 1 at the last layer prior to the reduces expressive output and it's different than the unet_learner in fastai v1. In fastai v1 roughly the same code produced:

```
ReLU                 [1, 99, 224, 224]    0          False     
______________________________________________________________________
MergeLayer           [1, 99, 224, 224]    0          False     
______________________________________________________________________
Conv2d               [1, 2, 224, 224]     200        True      
______________________________________________________________________
SigmoidRange         [1, 2, 224, 224]     0          False     
______________________________________________________________________
```
(just note the absence of BN in v1)

**Comment by sgugger** [comment]
Wait, why do you have Bathcnorm at all? The default (as in v1) is to not use any normalization on those convs.

**Comment by antorsae** [comment]
Well I'm at last commit (https://github.com/fastai/fastai2/commit/89559739f8f917450956fd7625d8fc218a917124) and invoking via 

`learn=unet_learner(dls,models.resnet34,n_in=3*h.seq_len,n_out=3,normalize=False,loss_func=MSELossFlat(),config={'y_range':(0,1), 'blur_final' : False})`

and with that it uses BNs in all Conv layers, including the one at the end.

**Comment by sgugger** [comment]
This default has been fixed.
