### ISSUE TITLE
create_head shows Full instead of Flatten

### ISSUE THREAD

**Issue by muellerzr** [fastai/fastai2#108]
When making a call to create_head, it will show a flattening layer as Full instead. This is strange to read unless you explore the source code. Can this be changed?

See here for an example:
https://forums.fast.ai/t/a-walk-with-fastai2-study-group-and-online-lectures-megathread/59929/631?u=muellerzr

**Comment by sgugger** [comment]
Fixed by [this commit](https://github.com/fastai/fastcore/commit/7ba02aa84b18ba54bf077d1aa98cb73ae1e59d13) in fastcore. You will need to update fastcore to the latest.

**Comment by muellerzr** [comment]
Thanks!
