### ISSUE TITLE
annealer decorator interferes with export

### ISSUE THREAD

**Issue by nestordemeure** [fastai/fastai2#127]
While working on a adding a scheduler to my implementation of [manifold mixup](https://github.com/nestordemeure/ManifoldMixupV2), I dicovered that I had a pickle error (`PicklingError: Can't pickle <function SchedCos at 0x7fa4e7bc9598>: it's not the same object as fastai2.callback.schedule.SchedCos`) when exporting my learner with `learn.export(path)`.

After a bit of digging, it was due to having a partially applied scheduler as one of my callback's member (ie: `self.scheduler = SchedCos(0.,1.)`).
It seems that the partially applied scheduler has the same symbol name as the original scheduler triggering a name ambiguity error when pickling it.

I was able to fix the issue for my use case by applying the bounds at the last moment but the error might touch any learner using a scheduling callback and stay undetected as long as you do not export the model.

The issue might be fixable at the [annealer decorator](https://github.com/fastai/fastai2/blob/master/nbs/14_callback.schedule.ipynb) level but I am not familiar enough with the internals of python to suggest a fix.

**Comment by sgugger** [comment]
Fixed for now, Jeremy will look at how to fix the decorator properly later.
