### ISSUE TITLE
2 images input issue

### ISSUE THREAD

**Issue by lvaleriu** [fastai/fastai2#128]
Here you can find a notebook that reproduces an issue I'm struggling with for some time. The scenario is the following:

- The URLs.CAMVID_TINY dataset
- A datablock with 2 Image inputs: DataBlock(blocks=(ImageBlock, ImageBlock, MaskBlock), ....)
- A custom class that handles 2 inputs (in this example it simply ignores the second image):

class CustomSequentialEx(SequentialEx):
    def forward(self, x, x2):
....

- A CustomDynamicUnet that is identic to the original DynamicUnet but has CustomSequentialEx as a base class.
- A Custom_unet_learner that is identic to the original unet_learner but initialises a CustomDynamicUnet instead.

and .... errors with learn.lr_find / learn.fit_one_cycle.

Can someone help me with this one. I'm out of ideas at the moment.

[https://colab.research.google.com/drive/1WRcKjBMkQFMZfF6JGSWqOs4qwaIoAS79](url)

**Comment by sgugger** [comment]
Please use the [forum](https://forums.fast.ai/) for debugging your code. We keep the issues for bugs in the library only.
