### ISSUE TITLE
Tensorboard Callback crashes when using Distributed Training

### ISSUE THREAD

**Issue by hussam789** [fastai/fastai2#13]
Hi,
Adding Tensorboard callback isn't supported when running in DDP, getting this error:
```
   self.writer = SummaryWriter(log_dir=self.log_dir)
  File "/opt/conda/lib/python3.6/site-packages/torch/utils/tensorboard/writer.py", line 221, in __init__
    mkdir(name, mode)
FileExistsError: [Errno 17] File exists: 'runs/Dec01_17-51-15_job-28573-chief-0'
```
I assume it should be a similar solution to how you it was handled in [SaveModelCallback](https://github.com/fastai/fastai_dev/pull/291)

**Comment by sgugger** [comment]
Thanks for flagging. I added a check to only run the callback in the master process (and also not during an LR finder/get_preds).

**Comment by hussam789** [comment]
Awesome, Thanks
