### ISSUE TITLE
`get_files` not excluding base folder

### ISSUE THREAD

**Issue by muellerzr** [fastai/fastai2#132]
When attempting to do the GAN example, I noticed I was picking up the original images too from the dataset. To reproduce, do the following:

```python
path = untar_data(URLs.PETS)
imgs = get_image_files(path, folders=['hello])
```
(Hello is not a folder available so thus it should be zero)
The following test will fail:
`test_eq(len(imgs), 0)`

**Comment by sgugger** [comment]
I have `len(imgs) = 0` in this case. I guess you mean that when you do `imgs = get_image_files(path, folders=['hello])`, it should be 0 unless '.' was in the list of folders.

**Comment by muellerzr** [comment]
Interesting. That wasn’t the behavior I was noticing, but I also wasn’t on the dev version. I’ll try again later today and see if that works

**Comment by sgugger** [comment]
That is the thing I fixed, please reopen the issue with a clearer example if it was not what you wanted.
