### ISSUE TITLE
 'Numericalize' object has no attribute 'sep'

### ISSUE THREAD

**Issue by lvaleriu** [fastai/fastai2#138]
When running `learn.predict("This was a good movie", n_words=10, temperature=0.75)` on a trained `fastai2.text.learner.LMLearner` instance I get this error:
(I'm running the 38_tutorial.ulmfit.ipynb notebook and added this prediction line before training the classifier/after training the language model)

`---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-17-e53fe635860e> in <module>
      1 #learn.predict("This was a good movie")
----> 2 learn.predict("This was a good movie", n_words=10, temperature=0.75)

~/workspace/fastai2/fastai2/text/learner.py in predict(self, text, n_words, no_unk, temperature, min_p, rm_type_tfms, no_bar, decoder, **kwargs)
    126 
    127         tokens = [tfm.vocab[i] for i in idxs if tfm.vocab[i] not in [BOS, PAD]]
--> 128         return tfm.sep.join(decoder(tokens))
    129 
    130     @delegates(Learner.get_preds)

AttributeError: 'Numericalize' object has no attribute 'sep'`

**Comment by lvaleriu** [comment]
This seems to be the commit that removed the attribute 'sep': [](https://github.com/fastai/fastai2/commit/c09c0f7ca54e6b96427ec92149e4e2a3c920bcf0)

**Comment by sgugger** [comment]
Thanks for flagging! Should be fixed now.
