### ISSUE TITLE
Calling all_reduce() in Distributed Traing

### ISSUE THREAD

**Issue by hussam789** [fastai/fastai2#14]
Calling `torch.distributed.all_reduce()` is needed In order to obtain the sum of all tensors (loss, top_accuracy...) at all processes when running in distributed training.
I saw that you already wrote a function that does exactly that [`_maybe_reduce(val)`](https://github.com/fastai/fastai2/blob/2af3272bad4e64334b5ab540657b63b2e3e4b1fa/fastai2/learner.py#L407) and I'm not sure if it used anywhere in the distributed callback or anywhere else in the training pipeline.

**Comment by sgugger** [comment]
Tensors are gathered in `to_detach` if there is a distributed training, making sure losses and metrics are computed appropriately.
