### ISSUE TITLE
AttributeError: tokenize

### ISSUE THREAD

**Issue by lvaleriu** [fastai/fastai2#142]
Similar to issue #138 

When running learn.predict("This was a good movie", n_words=10, temperature=0.75) on a trained fastai2.text.learner.LMLearner instance I get this error:
(I'm running the 38_tutorial.ulmfit.ipynb notebook and added this prediction line before training the classifier/after training the language model)

~/workspace/fastai2/fastai2/text/learner.py in predict(self, text, n_words, no_unk, temperature, min_p, rm_type_tfms, no_bar, decoder, **kwargs)
    126 
    127         tokens = [tfm.vocab[i] for i in idxs if tfm.vocab[i] not in [BOS, PAD]]
--> 128         sep = self.dls.train_ds.tokenize
    129         return sep.join(decoder(tokens))
    130 

~/workspace/fastai2/fastai2/data/core.py in __getattr__(self, k)
    266         return res if is_indexer(it) else list(zip(*res))
    267 
--> 268     def __getattr__(self,k): return gather_attrs(self, k, 'tls')
    269     def __dir__(self): return super().__dir__() + gather_attr_names(self, 'tls')
    270     def __len__(self): return len(self.tls[0])

~/workspace/fastcore/fastcore/transform.py in gather_attrs(o, k, nm)
    151     att = getattr(o,nm)
    152     res = [t for t in att.attrgot(k) if t is not None]
--> 153     if not res: raise AttributeError(k)
    154     return res[0] if len(res)==1 else L(res)
    155 

AttributeError: tokenize

**Comment by sgugger** [comment]
Sorry, forgot an `r`...
