### ISSUE TITLE
Dealing with copy Tabular Memory Issues

### ISSUE THREAD

**Issue by muellerzr** [fastai/fastai2#147]
I'm opening up this persistent issue while going through and attempting to manage the memory usage out of the `Tabular`. Currently, the first issue lies in here:

```python
class Tabular(CollBase, GetAttr, FilteredBase):
    "A `DataFrame` wrapper that knows which cols are cont/cat/y, and returns rows in `__getitem__`"
    _default,with_cont='procs',True
    def __init__(self, df, procs=None, cat_names=None, cont_names=None, y_names=None, block_y=None, splits=None,
                 do_setup=True, device=None):
        if splits is None: splits=[range_of(df)]
        print(hex(id(df)))
        df = df.iloc[sum(splits, [])]
        print(hex(id(df)))
        self.dataloaders = delegates(self._dl_type.__init__)(self.dataloaders)
```

If I look at the locations of the two, they wind up being different, which then adds another copy into memory. I think a partial solution here would be something like so:

```python
    def __init__(self, df, procs=None, cat_names=None, cont_names=None, y_names=None, block_y=None, splits=None,
                 do_setup=True, device=None):
        if splits is None: splits=[range_of(df)]
        if len(sum(splits)) < len(df):
          df = df.iloc[sum(splits, [])]
        self.dataloaders = delegates(self._dl_type.__init__)(self.dataloaders)
```
This way we always guarentee that we create a copy **if** it's a smaller dataframe. Doing so reduces the usage from an extra 662 mb to no added memory usage whatsoever. Let me know your thoughts @jph00 or @sgugger. I'll work on the rest when I can but this is a start

**Comment by sgugger** [comment]
Noted. 
In terms of organization, I'd rather have several addressable issues than one big issue that is never closed (in my experience those are then forgotten forever and never addressed). So let's keep this one specifically about the copy in-memory. I think we can work around this one with the `splits=None`. Will look.

**Comment by muellerzr** [comment]
Sounds good! I haven't tested how this translates over to `DataLoader` usage, but I'll try to look at that later this afternoon/tonight

**Comment by sgugger** [comment]
To experiment with this, I added back the inplace argument (default False to not break any current behavior). The iloc is only performed if splits is not None.

**Comment by muellerzr** [comment]
I think the issue lies with the `.copy()` we are using for generating the `DataFrame`, as this immediately doubles everything we want to use, and if we have a dataframe that's very very large this becomes very memory intensive. Do we mostly have it there for the `procs`? I assume also it's because when we are working on the dataframe we don't want to affect the original values?

**Comment by sgugger** [comment]
YEs, everything is done inplace for preprocessing. There is no copy anymore if you set `inplace=True` to Tabular though, so that should help with heavy dataframes.

**Comment by muellerzr** [comment]
Got it! Btw, inplace raises a `SettingWithCopyError: 
A value is trying to be set on a copy of a slice from a DataFrame` error. IIRC that's adjusting the chained_assignment to none

(pd.options.mode.chained_assignment = None)

**Comment by muellerzr** [comment]
Thanks! Just tried it and got the same footprint, so one fix :) I'll open up a new issue for something else i just found

**Comment by sgugger** [comment]
I guess the copy is mandatory if splits are passed then, will adjust.

**Comment by muellerzr** [comment]
It was? I didn’t notice an issue with that on my end. (Using RandomSplitter). When did it pop up?

**Comment by sgugger** [comment]
```

> Btw, inplace raises a `SettingWithCopyError: A value is trying to be set on a copy of a slice from a DataFrame` error.

That's what you reported. I guess I could make that fail more graciously by indicating the workaround you mentioned.

**Comment by sgugger** [comment]
Done, so closing this issue.

**Comment by muellerzr** [comment]
Awesome, thanks!

**Comment by muellerzr** [comment]
@sgugger the notice it seems to pop up even when you set it originally, and if it's still set to true. One fix (if it's already set) is to check if `pd.options.mode.chained_assignment` *is* none, but I'm unsure why it's always popping up (it will even do so on the call to `.dataloaders` I noticed
