### ISSUE TITLE
Memory Usage by Preprocessors

### ISSUE THREAD

**Issue by muellerzr** [fastai/fastai2#148]
Opening up a different issue here. On Rossmann if I do not preprocess my categorical datatypes, the footprint goes up by 1gb. However if I preprocess by doing:

```python
for name in cat_vars:
  train_df[name] = train_df[name].astype('category')
to = TabularPandas(train_df, procs=[Categorify], cat_names=cat_vars, cont_names=cont_vars,
                   y_names=dep_var, block_y=TransformBlock(), splits=splits, inplace=True)
```
the footprint stays at ~300mb's (the same as it was after doing the forced `astype`. I'll try to take a look.

**Comment by muellerzr** [comment]
For a better visualization:

Before converting:
```
              total        used        free      shared  buff/cache   available
Mem:          13022        1540        7518           0        3963       11624
Swap:             0           0           0
```
When doing the `for name etc`:
```
              total        used        free      shared  buff/cache   available
Mem:          13022        1817        7277           0        3928       12040
Swap:             0           0           0
```
(which stays the same after doing `TabularPandas`
Without doing so:
```
              total        used        free      shared  buff/cache   available
Mem:          13022        2829        6226           0        3966       11614
Swap:             0           0           0
```

**Comment by muellerzr** [comment]
I did some more work into looking into this. I adjusted the title of the issue to reflect what I looked into. Instead I compared how the memory usage changed in regards to each preprocessor, and here is what I found:

| Name | N rows | Pre-memory | Post-Memory | Secondary  Post-Memory  usage | Added Memory | % increase |
|:-----------------------------:|:-------:|:----------:|:-----------:|:-----------------------------:|--------------|------------|
| All 3 with no cat pre-process | 844338 | 1.53gb | 3.17gb |  | 1.64gb | 107.19 |
|  | 2000000 | 3.98gb | 6.61gb |  | 2.63gb | 66 |
| All 3 with cat pre-process | 844338 | 1.53gb | 1.81gb | 1.85gb | 0.32gb | 20.9 |
|  | 2000000 | 3.98gb | 3.87gb | 6.28gb | 2.3gb | 57.78 |
||||||||
| Categorify no pre-process | 844338 | 1.53gb | 2.40gb |  | 0.87gb | 56.86 |
|  | 2000000 | 3.98gb | 4.17gb |  | 0.19gb | 4.7 |
| Categorify with pre-process | 844338 | 1.53gb | 1.81gb | 1.85g | 0.32gb | 20.9 |
|  | 2000000 | 3.98gb | 3.96gb | 4.02gb | 0.02gb | 1 |
||||||||
| Normalize | 844338 | 1.53gb | 2.41gb |  | 0.87gb | 57.5 |
|  | 2000000 | 3.96gb | 6.40gb |  | 2.44gb | 61.6 |
||||||||
| FillMissing | 844338 | 1.54gb | 2.48gb |  | 0.94gb | 61.0 |
|  | 2000000 | 3.98gb | 4.99gb |  | 1.01gb | 25.0 |

Some interesting behavior is as the dataframe gets bigger, the added affect via Categorify (and FillMissing) seems to lower. I'm going to look at adjusting datatypes next for Normalize and FillMissing but I think in general some sort of guideline/warning should be posted about how to save up memory in the documentation :)

**Comment by muellerzr** [comment]
I know you guys are quite busy, so I’ll try to do a quick PR with what I have in mind with the memory fix and see. My thoughts were processing the float32 and then in the documentation note about preprocessing the categorical datatypes.

**Comment by sgugger** [comment]
I'd make the preprocessing a separate processor (that we can add by default), just so people can easily remove it if they find it annoying in their case.

**Comment by muellerzr** [comment]
Got it, I’ll look into that approach
