### ISSUE TITLE
tagging versions in github

### ISSUE THREAD

**Issue by foobar8675** [fastai/fastai2#149]
this is a request, and not an issue.

Is it possible to tag pip versions in github, like what was done in v1? I'm trying out ipdb like 
```
b fastai2/learner.py:468
```
and since what is in pip might not be what is in sync with github:master, finding the right line number can be a bit tedious. I'm glad to help out with this as well. 

fastai v1 screenshot.

![Screen Shot 2020-03-05 at 4 22 40 PM](https://user-images.githubusercontent.com/1685700/76038098-994e3e00-5efd-11ea-8717-7bc21f38df72.png)

**Comment by sgugger** [comment]
We are still in a development stage, we'll do this once we move fastai2 to the main repo, but not before.
