### ISSUE TITLE
SchedLin error

### ISSUE THREAD

**Issue by mrT23** [fastai/fastai2#15]
i am trying to use SchedLin callback
`
lr_max = np.array([h['lr'] for h in learn.opt.hypers]) 
scheds = {
        'lr': combine_scheds([pct_start, 1 - pct_start], [SchedLin(lr_max / 10, lr_max), SchedCos(lr_max, 1e-4)])}
    learn.fit(n_epoch, cbs=ParamScheduler(scheds), wd=wd)
`

and i get an error

>   File "\fastai2\callback\schedule.py", line 20, in SchedLin
    return start + pos*(end-start)
TypeError: mul(): argument 'other' (position 1) must be Tensor, not numpy.ndarray

**Comment by sgugger** [comment]
Thanks for flagging! It should be fixed now.
