### ISSUE TITLE
tabular_learner get_emb_sz is called on emb_szs if given

### ISSUE THREAD

**Issue by bezova** [fastai/fastai2#151]
in tabular/learner.py:`tabular_learner` function we have embedings size calculation

25:  `emb_szs = get_emb_sz(dls.train_ds, {} if emb_szs is None else emb_szs)`

which is calling `get_emb_sz(emb_szs)` if emb_szs is provided

this will produce Error if provided `emb_szs`  was product of `get_emb_sz(to)` :
>  'list' object has no attribute 'get'

looks like its a typo, suggested fix: move the ")":

`emb_szs = get_emb_sz(dls.train_ds, {}) if emb_szs is None else emb_szs
`

**Comment by sgugger** [comment]
No, `emv_szs` is supposed to be a dictionary key to size (so you can choose the sizes of some, but still use the default for others).
