### ISSUE TITLE
dls.cpu failes when using Nomalize

### ISSUE THREAD

**Issue by cwza** [fastai/fastai2#158]
``` python
items = [TensorImage(torch.randint(0, 255, (3, 64, 64))) for _ in range(100)]
dsets = Datasets(items=items)
dls = dsets.dataloaders(bs=2, after_batch=[IntToFloatTensor(), Normalize.from_stats(*imagenet_stats)])
dls.one_batch()[0].device
```
`device(type='cuda', index=0)`
``` python
dls.cpu()
dls.one_batch()[0].device
```
`RuntimeError: expected device cpu but got device cuda:0`

I found that normalize object stores mean and std while init. Perhaps the dls forgot to change them??

**Comment by sgugger** [comment]
Thanks for flagging this! It should be fixed now.
