### ISSUE TITLE
fastcore.all import error

### ISSUE THREAD

**Issue by cbinners** [fastai/fastai2#16]
I know you're in the middle of refactoring, but I'm getting the following error:

```
~/projects/fastai2/fastai2/imports.py in <module>
     27 from scipy import ndimage
     28 from IPython.core.debugger import set_trace
---> 29 from fastcore.all import *
     30 from fastprogress.fastprogress import progress_bar, master_bar
     31 

ModuleNotFoundError: No module named 'fastcore.all'
```

I forked the fastcore repo to attempt to solve it locally, but I'm unsure how to configure the nbdev settings to build the `all.py` file as found in many of the fastai modules.

Is there something I can do locally to resolve this for now?

**Comment by cbinners** [comment]
Solved for now by manually adding an `all.py` file with the imports.

`fastcore/all.py`
```python
from .dispatch import *
from .foundation import *
from .imports import *
from .script import *
from .test import *
from .transform import *
from .utils import *
```

**Comment by sgugger** [comment]
Oh did I forget to push this? Sorry.

**Comment by sgugger** [comment]
All done now, I'll make a release tonight with that change.
