### ISSUE TITLE
TypeError: 'function' object cannot be interpreted as an integer

### ISSUE THREAD

**Issue by lvaleriu** [fastai/fastai2#162]
When running _from fastai2.data.transforms import get_image_files_ in the 24_tutorial.siamese.ipynb notebook I get the following error:
`
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-1-020b35802034> in <module>
      1 from fastai2.data.external import untar_data,URLs
----> 2 from fastai2.data.transforms import get_image_files

~/workspace/fastai2/fastai2/data/transforms.py in <module>
     10 # Cell
     11 from ..torch_basics import *
---> 12 from .core import *
     13 from .load import *
     14 from .external import *

~/workspace/fastai2/fastai2/data/core.py in <module>
    114 # Cell
    115 @docs
--> 116 class DataLoaders(GetAttr):
    117     "Basic wrapper around several `DataLoader`s."
    118     _default='train'

~/workspace/fastai2/fastai2/data/core.py in DataLoaders()
    127 
    128     def _set(i, self, v): self.loaders[i] = v
--> 129     train   ,valid    = add_props(lambda i,x: x[i], _set)
    130     train_ds,valid_ds = add_props(lambda i,x: x[i].dataset)
    131 

~/workspace/fastcore/fastcore/utils.py in add_props(f, n)
    530 def add_props(f, n=2):
    531     "Create properties passing each of `range(n)` to f"
--> 532     return (property(partial(f,i)) for i in range(n))
    533 
    534 # Cell

TypeError: 'function' object cannot be interpreted as an integer
`

**Comment by lvaleriu** [comment]
Needed to update fastcore ...

**Comment by noklam** [comment]
@lvaleriu  may i ask what is your fastcore version? I upgrade to 0.1.14 but still sufferf rom same issue.

**Comment by nvs-abhilash** [comment]
It should work with the master branch of `fastcore`. master is at `0.1.15`

**Comment by MotorCityCobra** [comment]
I do `pip3 install fastcore` but it doesn't work.  
How do I get fastcore master 0.1.15 exactly?

**Comment by noklam** [comment]
@MotorCityCobra you need to install the git master branch instead...
Git clone the fastcore repo
Pip install -e fastcore

**Comment by nvs-abhilash** [comment]
> I do `pip3 install fastcore` but it doesn't work.
> How do I get fastcore master 0.1.15 exactly?

You can directly install it from got also. Look at this comment from similar issue: https://github.com/fastai/fastai2/issues/167#issuecomment-598509329

**Comment by jekriske-lilly** [comment]
Ran into this today. It'd be great if `pip install -U fastai2` pulled in the correct fastcore.
