### ISSUE TITLE
Can't download MNIST_SAMPLE or PLANET_TINY on AWS

### ISSUE THREAD

**Issue by austinmw** [fastai/fastai2#163]
Hi, on a SageMaker hosted notebook in us-east-2 region, I'm not able to wget `http://files.fast.ai/data/examples/mnist_sample.tgz` or `http://files.fast.ai/data/examples/planet_tiny.tgz`. They seem to not be able to connect:

```
--2020-03-11 23:53:08--  http://files.fast.ai/data/examples/mnist_sample.tgz
Resolving files.fast.ai (files.fast.ai)... 67.205.15.147
Connecting to files.fast.ai (files.fast.ai)|67.205.15.147|:80... 
```
However on my local desktop it works. I'm not sure whether this issue is actually on fastai's side, but I don't appear to be limited in retrieving any other files. I can also get the full versions of the datasets in SageMaker just fine, since I guess they're hosted on AWS already.

**Comment by sgugger** [comment]
I think this comes from AWS, not us. I can download those files just fine.
