### ISSUE TITLE
[bug] show_batch show wrong  result for laguage model problem

### ISSUE THREAD

**Issue by richardyy1188** [fastai/fastai2#164]
# Problem
In `35_tutorial.wikitext.ipynb`, set `seq_len` larger than 150,  
and found `show_batch()` print extra words in `_text` column.
```
                      text            |               _text
-----------------------------------------------------------------------------------------------  
Expect: a popular instead ... how the | popular instead of ... how the power
-----------------------------------------------------------------------------------------------  
Get:    a popular instead ... how the | popular instead of ... how the power the xxmaj
-----------------------------------------------------------------------------------------------
```
# Note
- Batchs loaded from dataloader are correct, both x and y has shape of [batchsize, seq_len] and token ids follow the rule of laguage model problem.
- `seq_len` <= 150  behaves normally, but when > 150, we'll get `seq_len` - 150 extra words that we don't want to see in `_text` column

**Comment by sgugger** [comment]
Thanks for flagging, should be fixed now!
