### ISSUE TITLE
untar_data extract to different name

### ISSUE THREAD

**Issue by tcapelle** [fastai/fastai2#166]
The issue I am having is when `untar_data` is downloading and extracting a folder that has a name different than the `.zip`:
Example:
You have a file `folder_a.zip` than unzips to `folder_b.zip`. The `untar_data` function returns the path to unzipped `folder_a` that does not exist. 

This has an easy fix, or we rename the folder to 'folder_a' or we return a Path object o 'folder_b'.
Tell me which option do you prefer and I can fix it.

**Comment by sgugger** [comment]
`untar_data` won't work if your decompressed data has a different name, that's true. I guess renaming the decompressed folder is the best solution if it's not too much work. Otherwise, I'd just drop it, `untar_data` is meant to work outside of the fastai URLs.

**Comment by tcapelle** [comment]
I will propose a fix renaming the output folder.
It is a very useful method for datasets stored over the internet.

**Comment by sgugger** [comment]
Not saying this wouldn't be a useful functionality, just saying it's not one we have actively developed ;)

**Comment by sgugger** [comment]
Are you still working on this?

**Comment by tcapelle** [comment]
I will do this sometimes this week!
Sorry, a little bit under the water...

**Comment by sgugger** [comment]
Fixed by #269
