### ISSUE TITLE
Error in pip install -e ".[dev]" after git clone https://github.com/fastai/fastai2; cd fastai2

### ISSUE THREAD

**Issue by jcatanza** [fastai/fastai2#181]
`On 64-bit Windows 10 system`

**Comment by jcatanza** [comment]
`(fastai2) C:\Users\cross-entropy\fastai\fastai2>pip install -e ".[dev]"`
Obtaining file:///C:/Users/cross-entropy/fastai/fastai2
Collecting fastcore
  Using cached fastcore-0.1.14-py3-none-any.whl (27 kB)
ERROR: Could not find a version that satisfies the requirement torch>=1.3.0 (from fastai2==0.0.12) (from versions: 0.1.2, 0.1.2.post1, 0.1.2.post2)
ERROR: No matching distribution found for torch>=1.3.0 (from fastai2==0.0.12)

**Comment by nvs-abhilash** [comment]
If I am not wrong, you first need to install the dependencies. An easier way to do that would be to use conda. 

```
conda env create -f environment.yml
source activate fastai2
```

It is straight from README here: [Installing](https://github.com/fastai/fastai2/blob/master/README.md#installing)

**Comment by jcatanza** [comment]
I'm working from the same README.
Since I am on a Windows 10 64-bit system, I had run the commands
````
conda create -n fastai2 python-3.8.1 anaconda`
`activate fastai2`
```
which should be equivalent, prior to receiving the error message.

**Comment by nvs-abhilash** [comment]
Not really, `conda create -n fastai2 python-3.8.1 anaconda` creates an environment named fastai2 with `anaconda` packages. But `conda env create -f environment.yml` does something different. It reads the dependencies listed in [`environment.yml`](https://github.com/fastai/fastai2/blob/master/environment.yml) and installs them in an environment called `fastai2`.

**Comment by sgugger** [comment]
I tested on Windows and the steps do work there.
