### ISSUE TITLE
Is it possible to get the names of misinterpreted images with plot_top_losses ?

### ISSUE THREAD

**Issue by aquadzn** [fastai/fastai2#185]
Hello,

as shown in this image
<a href="https://imgbb.com/"><img src="https://i.ibb.co/kmr90Xz/index.png" alt="index" border="0"></a>

is it possible to get the filenames of misinterpreted images after using `plot_top_losses` ?

Thanks

**Comment by sgugger** [comment]
That would require quite a lot of changes to the architecture sadly. You can get the indices of those images with:
```
losses,idx = self.top_losses(k, largest)
```
and give the value of k you want, and then look at the corresponding items in the dataset you are using however.

Closing the issue, we can discuss more on the forum if this is not enough.
