### ISSUE TITLE
export model pickle overflow error

### ISSUE THREAD

**Issue by DmitriyG228** [fastai/fastai2#188]
Hi, while exporting models larger, then 4 gigabytes there is a pickle overflow error. This is usually easily fixed with protocol=4 parameter in pickle.dump. Please consider updating the source code for the export method. Thank you!

**Comment by sgugger** [comment]
Note that we are not calling `pickle.dump` but `torch.save`. I can make that argument surface if helpful.

**Comment by DmitriyG228** [comment]
Yes, that would be definitely helpful and even making it a default setting will benefit everyone imho.
