### ISSUE TITLE
xresnet meta.cut should be -4

### ISSUE THREAD

**Issue by bearpelican** [fastai/fastai2#19]
Looks like there's 4 layers in the head:
https://github.com/fastai/fastai2/blob/master/fastai2/vision/models/xresnet.py#L41

However, cut says -4
https://github.com/fastai/fastai2/blob/master/fastai2/vision/learner.py#L86

Test case:
`test_eq(bool(_is_pool_type(models.xresnet.xresnet34()[_xresnet_meta['cut']])), True)`

**Comment by sgugger** [comment]
It depends of the value of your dropout, but I made it always 4.
