### ISSUE TITLE
Sentencepiece.Trainer can't find tmp/texts.out

### ISSUE THREAD

**Issue by RogerS49** [fastai/fastai2#190]
Please refer to this 

https://forums.fast.ai/t/nb-10-error-cant-open-tmp-texts-out/66011/5

I can't prove this because my knowledge of egg and sentencepiece is limited 

Thanks

**Comment by nvs-abhilash** [comment]
The link provided is not public.

**Comment by sgugger** [comment]
Should be fixed now, confirmed the notebooks are running.
