### ISSUE TITLE
"bernoulli_scalar_cpu_" not implemented for 'Half' 

### ISSUE THREAD

**Issue by RogerS49** [fastai/fastai2#197]
See

https://github.com/pytorch/pytorch/issues/25946

There seems some incorrect behaviour  when fine tuning in 10_nlp.ipynb

Here is runtime printout with debug 
> /home/dl/fastai-2020/fastai2/fastai2/text/models/awdlstm.py(14)dropout_mask()
     12 def dropout_mask(x, sz, p):
     13     "Return a dropout mask of the same type as `x`, size `sz`, with probability `p` to cancel an element."
---> 14     return x.new(*sz).bernoulli_(1-p).div_(1-p)
     15 
     16 # Cell

ipdb> a
x = tensor([[-0.1276,  0.0161,  0.1617,  ..., -0.1396,  0.6899, -0.0399],
        [ 0.0272,  0.0011,  0.0401,  ...,  0.0161,  0.0666, -0.0014],
        [ 0.6069, -0.5239,  0.1544,  ..., -0.2551, -0.3308, -0.0702],
        ...,
        [ 0.0253,  0.0026,  0.0423,  ...,  0.0128,  0.0848, -0.0018],
        [ 0.0253,  0.0026,  0.0423,  ...,  0.0128,  0.0848, -0.0018],
        [ 0.0253,  0.0026,  0.0423,  ...,  0.0128,  0.0848, -0.0018]], dtype=torch.float16)
sz = (60008, 1)
p = 0.006
ipdb> c

epoch 	train_loss 	valid_loss 	accuracy 	perplexity 	time
0 	0.000000 	00:02

---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-33-d69d080df093> in <module>
      1 get_ipython().run_line_magic('debug', '')
----> 2 learn.fit_one_cycle(1, 2e-2)

~/fastai-2020/fastai2/fastai2/callback/schedule.py in fit_one_cycle(self, n_epoch, lr_max, div, div_final, pct_start, wd, moms, cbs, reset_opt)
    110     scheds = {'lr': combined_cos(pct_start, lr_max/div, lr_max, lr_max/div_final),
    111               'mom': combined_cos(pct_start, *(self.moms if moms is None else moms))}
--> 112     self.fit(n_epoch, cbs=ParamScheduler(scheds)+L(cbs), reset_opt=reset_opt, wd=wd)
    113 
    114 # Cell

~/fastai-2020/fastai2/fastai2/learner.py in fit(self, n_epoch, lr, wd, cbs, reset_opt)
    190                     try:
    191                         self.epoch=epoch;          self('begin_epoch')
--> 192                         self._do_epoch_train()
    193                         self._do_epoch_validate()
    194                     except CancelEpochException:   self('after_cancel_epoch')

~/fastai-2020/fastai2/fastai2/learner.py in _do_epoch_train(self)
    163         try:
    164             self.dl = self.dls.train;                        self('begin_train')
--> 165             self.all_batches()
    166         except CancelTrainException:                         self('after_cancel_train')
    167         finally:                                             self('after_train')

~/fastai-2020/fastai2/fastai2/learner.py in all_batches(self)
    141     def all_batches(self):
    142         self.n_iter = len(self.dl)
--> 143         for o in enumerate(self.dl): self.one_batch(*o)
    144 
    145     def one_batch(self, i, b):

~/fastai-2020/fastai2/fastai2/learner.py in one_batch(self, i, b)
    147         try:
    148             self._split(b);                                  self('begin_batch')
--> 149             self.pred = self.model(*self.xb);                self('after_pred')
    150             if len(self.yb) == 0: return
    151             self.loss = self.loss_func(self.pred, *self.yb); self('after_loss')

~/anaconda3/envs/fastai2/lib/python3.7/site-packages/torch/nn/modules/module.py in __call__(self, *input, **kwargs)
    530             result = self._slow_forward(*input, **kwargs)
    531         else:
--> 532             result = self.forward(*input, **kwargs)
    533         for hook in self._forward_hooks.values():
    534             hook_result = hook(self, input, result)

~/anaconda3/envs/fastai2/lib/python3.7/site-packages/torch/nn/modules/container.py in forward(self, input)
     98     def forward(self, input):
     99         for module in self:
--> 100             input = module(input)
    101         return input
    102 

~/anaconda3/envs/fastai2/lib/python3.7/site-packages/torch/nn/modules/module.py in __call__(self, *input, **kwargs)
    530             result = self._slow_forward(*input, **kwargs)
    531         else:
--> 532             result = self.forward(*input, **kwargs)
    533         for hook in self._forward_hooks.values():
    534             hook_result = hook(self, input, result)

~/fastai-2020/fastai2/fastai2/text/models/awdlstm.py in forward(self, inp, from_embeds)
     97         if bs!=self.bs: self._change_hidden(bs)
     98 
---> 99         output = self.input_dp(inp if from_embeds else self.encoder_dp(inp))
    100         new_hidden = []
    101         for l, (rnn,hid_dp) in enumerate(zip(self.rnns, self.hidden_dps)):

~/anaconda3/envs/fastai2/lib/python3.7/site-packages/torch/nn/modules/module.py in __call__(self, *input, **kwargs)
    530             result = self._slow_forward(*input, **kwargs)
    531         else:
--> 532             result = self.forward(*input, **kwargs)
    533         for hook in self._forward_hooks.values():
    534             hook_result = hook(self, input, result)

~/fastai-2020/fastai2/fastai2/text/models/awdlstm.py in forward(self, words, scale)
     67         if self.training and self.embed_p != 0:
     68             size = (self.emb.weight.size(0),1)
---> 69             mask = dropout_mask(self.emb.weight.data, size, self.embed_p)
     70             masked_embed = self.emb.weight * mask
     71         else: masked_embed = self.emb.weight

~/fastai-2020/fastai2/fastai2/text/models/awdlstm.py in dropout_mask(x, sz, p)
     12 def dropout_mask(x, sz, p):
     13     "Return a dropout mask of the same type as `x`, size `sz`, with probability `p` to cancel an element."
---> 14     return x.new(*sz).bernoulli_(1-p).div_(1-p)
     15 
     16 # Cell

RuntimeError: "bernoulli_scalar_cpu_" not implemented for 'Half'

**Comment by sgugger** [comment]
You are trying to train in mixed precision without a GPU, which does not work because CPUs don't support half-precision operations. Remove the line `to_fp16` from your `Learner` or train your model in an environment with a GPU.

**Comment by RogerS49** [comment]
Thanks . Sorry to trouble you. I must have missed the wording around that subject of cpu/gpu. FYI the environment I have has a GPU, but I’ll remove the line ‘to_fp16’ and try again tomorrow.

regards

RogerS49

**Comment by puraminy** [comment]
I also have GPU, yet get the error.

if I remove to_fp16, what should I replace for it?

**Comment by gshguru** [comment]
> if I remove to_fp16, what should I replace for it?
Nothing. just comment it out. It worked for me
