### ISSUE TITLE
cannot perform reduction function argmin on a tensor with no elements because the operation does not have an identity

### ISSUE THREAD

**Issue by WaterKnight1998** [fastai/fastai2#202]
Getting next error in lr_find() after unfreezing the learner:

`cannot perform reduction function argmin on a tensor with no elements because the operation does not have an identity`

**Comment by sgugger** [comment]
Please refer to [this topic](https://forums.fast.ai/t/how-to-debug-your-code-and-ask-for-help-with-fastai-v2/64196) on the forum. There is absolutely nothing we can do with just an error message like this.
