### ISSUE TITLE
AttributeError: 'L' object has no attribute 'truncate'

### ISSUE THREAD

**Issue by rraminen** [fastai/fastai2#204]

**Comment by rraminen** [comment]
I am working on lesson7-human-numbers.ipynb notebook and got the below error:

![image](https://user-images.githubusercontent.com/62723901/77697843-9800b600-6f7d-11ea-9a39-c5d16b791a01.png)

Please help.

**Comment by sgugger** [comment]
Fixed for now by removing that cell.

**Comment by rraminen** [comment]
Thank you
