### ISSUE TITLE
ValueError: This DataLoader does not contain any batches

### ISSUE THREAD

**Issue by rraminen** [fastai/fastai2#205]
I am getting the below errors while running _24_vision.gan.ipynb and lesson7-wgan.ipynb notebooks.
![image](https://user-images.githubusercontent.com/62723901/77698837-4c4f0c00-6f7f-11ea-9747-700a5081fa37.png)
![image](https://user-images.githubusercontent.com/62723901/77698968-84564f00-6f7f-11ea-8df9-8a178171b2df.png)
Please help.

**Comment by sgugger** [comment]
GAN are not fully ported yet. That's why the notebook has an _, it's not ready yet. I will put an _ to the lesson7-wgan notebook as well.

**Comment by rraminen** [comment]
Thanks for the information

**Comment by tyoc213** [comment]
so if this is closed, gans are now supported?
