### ISSUE TITLE
Not possible to set fixed seeds for reproducibility 

### ISSUE THREAD

**Issue by AnelMusic** [fastai/fastai2#208]
Setting fixed seed e.g. np.random.seed(42) does not enable reproducibility of Training results.
Even though randomness is important in practice for demonstration purposes it would be useful to disable randomness. 
This was possible in fastaiV1

**Comment by sgugger** [comment]
I would need more details than this. Setting the numpy seed is not enough to ensure reproducibility btw.

**Comment by sgugger** [comment]
Found the relevant forum thread and fixed. Will comment there too.
