### ISSUE TITLE
ImageDataLoaders.from_folder() pulls from other subfolders than train and valid

### ISSUE THREAD

**Issue by slawekslex** [fastai/fastai2#210]
I encountered it on the URLs.DOGS dataset. The directory structure is
<pre>
   dogscats
     --train
     --valid
     --samples
       --train
       --valid
</pre>
When I do `ImageDataLoaders.from_folder()` it will add the files from the samples directory to my train and valid sets which I found unexpected.

A way to fix it would be changing `get_items=get_image_files` into `get_items=partial(get_image_files, folders = [train, valid])` in the `from_folder` implementation.

Unless of course this is the desired behaviour in which I case I'll just get around it in my code.

**Comment by sgugger** [comment]
It's not that this is the desired behavior more than this is a specific function that only works for data set a certain way. All users should graduate to the data block API as soon as the API doesn't suit their needs.
For this specifically, I can see if there is an easy way to fix (cause it's not always train and valid inside).

**Comment by slawekslex** [comment]
Hi!
Thanks for the fix, but I believe you've made a mistake
[this line](https://github.com/fastai/fastai2/blob/323766b1667a44deb4f84aa2c9cab7cdd40cc7aa/fastai2/vision/data.py#L89) should read `get_items=get_items` not `get_image_files`

**Comment by sgugger** [comment]
Me, making a mistake? Impossible ;)
Thanks for the catch, should be really fixed now.
