### ISSUE TITLE
learn.lr_find AttributeError 

### ISSUE THREAD

**Issue by randywreed** [fastai/fastai2#216]
`learn = Learner(dls, fasthugs_model, opt_func=opt_func, splitter=splitter, loss_func=loss, cbs=cbs, metrics=[accuracy])
`
`learn.lr_find(show_plot=True)`

produces error:
AttributeError                            Traceback (most recent call last)
/content/fastai2/fastai2/learner.py in fit(self, n_epoch, lr, wd, cbs, reset_opt)
    187             try:
--> 188                 self._do_begin_fit(n_epoch)
    189                 for epoch in range(n_epoch):

26 frames
AttributeError: 'str' object has no attribute 'type'

During handling of the above exception, another exception occurred:

AttributeError                            Traceback (most recent call last)
/usr/local/lib/python3.6/dist-packages/fastprogress/fastprogress.py in on_iter_end(self)
    155             total_time = format_time(time.time() - self.main_bar.start_t)
    156             self.text = f'Total time: {total_time} <p>' + self.text
--> 157         self.out.update(HTML(self.text))
    158 
    159     def add_child(self, child):

AttributeError: 'NBMasterBar' object has no attribute 'out'

Run in Google Colab
Setup as specified elsewhere:
`
!pip install transformers`
`!git clone https://github.com/fastai/fastai2`
`%cd fastai2`
`!pip install -e ".[dev]"`
`!pip uninstall --y fastprogress`
`!pip install git+https://github.com/fastai/fastprogress --upgrade
`

**Comment by sgugger** [comment]
It's impossible to fix your problem without seeing the code you have executed. There is a problem when you try to train, that could come either from the data collection, the model, the loss function, the optimizer, and just giving the last line of the error message is not enough.

Please use the [forum](https://forums.fast.ai) to debug your code as we keep issues for known bugs only. Please refer to [this topic](https://forums.fast.ai/t/how-to-debug-your-code-and-ask-for-help-with-fastai-v2/64196) to efficiently ask for help.
