### ISSUE TITLE
Encoding of segmentation masks

### ISSUE THREAD

**Issue by tcapelle** [fastai/fastai2#219]
I am trying the segmentation pipeline on a dataset I have at work that has images that are encoded "differently".
My masks have 3 categories, so in the tensor we get values in [0, 122, 255]. 
Using the standard `MaskBlock` does not work, because the `IntToFloatTensor` encodes function does not handle this automatically:
 ```
class IntToFloatTensor(Transform):
    def encodes(self, o:TensorMask ): return o.div_(self.div_mask).long()
```
As one would like, the `y` output should be mapped to [0,1,2] to be able to compare outputs of the `unet(n_out=3)`.

- Should we deal with this automatically?

My fix was to build a `CustomMaskBlock` adding a transform before the `IntToFloatTensor`.
Masks are not always encoded with incresing ints from zero.

**Comment by sgugger** [comment]
I think you can pass `IntToFloatTensor(div_mask=122)` to achieve your results. In general, `MaskBlock` is not supposed to automatically map values to codes from 0 to nc. Just finding the values is a very long process and then doing the mapping at each iteration would be a very inefficient process. You should preprocess your masks once and for all.

**Comment by tcapelle** [comment]
This is what I finally did ;o
