### ISSUE TITLE
AttributeError: type object 'Image' has no attribute 'size'

### ISSUE THREAD

**Issue by floscha** [fastai/fastai2#22]
Hi, after installing fastai2 through pip, I get the following error when trying to call `from fastai2.callback.all import *`:

```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-2-74228919d9ab> in <module>()
      1 from fastai2.basics import *
      2 from fastai2.tabular.all import *
----> 3 from fastai2.callback.all import *

2 frames
/usr/local/lib/python3.6/dist-packages/fastai2/vision/core.py in <module>()
     19 #Cell
     20 if not hasattr(Image,'_patched'):
---> 21     _old_sz = Image.Image.size.fget
     22     @patch_property
     23     def size(x:Image.Image): return Tuple(_old_sz(x))

AttributeError: type object 'Image' has no attribute 'size'
```

Could this problem be caused by a specific version of PIL or the patching logic itself?

**Comment by muellerzr** [comment]
Upgrade your PIL version and then restart your instance. That’s what’s needed.

**Comment by floscha** [comment]
That solved the problem for me. Thanks!

**Comment by sreejithmm** [comment]
> Upgrade your PIL version and then restart your instance. That’s what’s needed.

AttributeError: type object 'Image' has no attribute 'size'

I am also getting this error.
I have
Pillow             7.2.0
which is latest?

what I am missing?
