### ISSUE TITLE
Error in lesson7-superres.ipynb

### ISSUE THREAD

**Issue by rraminen** [fastai/fastai2#224]
I got the below error while running lesson7-superres.ipynb notebook
![image](https://user-images.githubusercontent.com/62723901/77943704-47da6a00-7283-11ea-8324-149955ef9a1c.png)
Fix:
Replace 
dls = get_dbunch(bs,size)
with
dls = get_dls(bs,size)

**Comment by sgugger** [comment]
Thanks for the pointer, fixed now. Note that when you have the fix, you can suggest a PR with it instead of filing a bug :)
