### ISSUE TITLE
10_tutorial.pets return type annotation

### ISSUE THREAD

**Issue by lgvaz** [fastai/fastai2#228]
In the notebook `10_tutorial.pets` just after we create `SiamesePair` we have the following text:

_... This kind of filtering is done with type annotations. We indicated with the return type annotation of `SiamesePair.encodes`..._

But we are not actually using return type annotations, we are just returning the correct type. A return type annotation would be something like:
```python
def encodes(self, i)->SiameseImage:
```
I recall that fastai used to use this return type annotations, is that still happening?

**Comment by sgugger** [comment]
The tutorial has not been updated in a while. It's the next on my list so this will be solved soon.

**Comment by lgvaz** [comment]
Yes, I'm following the list on the forums, this is exactly why I opened the issue =)
