### ISSUE TITLE
NameError: name 'gpu_mem_get_free_no_cache' is not defined

### ISSUE THREAD

**Issue by rraminen** [fastai/fastai2#230]
The below error is from lesson3-camvid.ipynb notebook:
![image](https://user-images.githubusercontent.com/62723901/78089456-177ef280-738d-11ea-8bab-d45de97badc1.png)

I could see that the definition of gpu_mem_get_free_no_cache() in fastai ( https://github.com/fastai/fastai/blob/master/fastai/utils/mem.py ) 

Is this module currently under development for fastai 2 or can I use it from fastai/utils/mem.py ?

**Comment by sgugger** [comment]
You should use it from fastai utils for now.
