### ISSUE TITLE
Not able to import vision package in Colab GPU runtime

### ISSUE THREAD

**Issue by puneethmishra** [fastai/fastai2#257]
While trying to import vision package:
from fastai2.vision.all import *
the error is NameError: name 'log_args' is not defined

**Comment by borisdayma** [comment]
You also need to have latest fastcore (git install)

**Comment by puneethmishra** [comment]
Tried this one to install fastai2

!pip install git+https://github.com/fastai/fastai2.git

**Comment by borisdayma** [comment]
You need to do the same with fastcore

**Comment by sgugger** [comment]
Indeed, you need both github versions together:
```
!pip install git+https://github.com/fastai/fastcore.git
!pip install git+https://github.com/fastai/fastai2.git
```

**Comment by puneethmishra** [comment]
Thanks a lot it worked fine now
