### ISSUE TITLE
Tuple transform is in docs, but not in code

### ISSUE THREAD

**Issue by ducha-aiki** [fastai/fastai2#266]
Hi, 

I think, docs might need to be updated: there is no TupleTransform anymore:

https://dev.fast.ai/core.transform.html#TupleTransform
![image](https://user-images.githubusercontent.com/4803565/78544159-01908800-77fa-11ea-9268-840104f758cf.png)

![image](https://user-images.githubusercontent.com/4803565/78544166-05bca580-77fa-11ea-97c9-e7e3a813d66a.png)

![image](https://user-images.githubusercontent.com/4803565/78544233-1d942980-77fa-11ea-97d9-2e1cffde51dc.png)

**Comment by sgugger** [comment]
I'm not sure how you accessed that page since it's not in the navigation bar anymore. Will remove it, thanks for flagging it's still there!

**Comment by ducha-aiki** [comment]
I used "search bar" for it. Reason I used search bar is that I have seen it in some example, cannot remember which one...

**Comment by sgugger** [comment]
It used to exist, but it's removed now since all transforms have his behavior (applying over tuple) unless they are `ItemTransform`.

**Comment by sgugger** [comment]
Fixed by removing those html files.
