### ISSUE TITLE
drop_last=True on valid dataset

### ISSUE THREAD

**Issue by tcapelle** [fastai/fastai2#267]
I am unable to have this behavior on the validation dataset.
I am using the `DataBlock` API, I think the problem is that the `FilteredBase` definition, (the inherited by `Dataset`) has this value hardcoded on the method `dataloaders`:
```python
dls = [dl] + [dl.new(self.subset(i), bs=(bs if val_bs is None else val_bs), shuffle=False, drop_last=False, 
                   n=None, **dl_kwargs[i]) for i in range(1, self.n_subsets)]
```
I could make a PR, but don't know what the "right" way of doing is.

**Comment by sgugger** [comment]
Yes, it is hard-coded because there is no use validating on part of your dataset only. We won't change that, but you can force it with:
```
dls.valid = dls.valid.new(drop_last=True)
```
This is a sign your model won't be able to perform at inference on various shapes though, if you must do this for validation to work.

**Comment by tcapelle** [comment]
I have a model that needs the `drop_last=True` cause the LSTM layers like a constant `batch_size`.
Any tips on dealing with this?

**Comment by sgugger** [comment]
I told you how you could force it in my reply. 
But if you need to use your model in production, you won't be able to cause the batch size will likely change, so you should make your model batch size-invariant.

**Comment by tcapelle** [comment]
My question is more general, how to deal with LSTM layers, and the last batch.
As the `hidden` size of the LSTM layer will be of the size of the batch, so I will have a problem feeding this last batch the the lstm layer.
Should I slice the hidden state ?  to feed only the `reduced` batch size of the last batch?
I may post this on the forums.

**Comment by sgugger** [comment]
It depends on your problem: for language modeling, the LMDataLoader ensures the last partial batch is always dropped because there is no way to deal with it.

For text classification, the state is reset at each new batch, so you can change the batch size.

Foloowing-up on the forum sounds good :)

**Comment by tcapelle** [comment]
Even with your fix does not work, as `_do_epoch_validate` will override my `drop_last`
```
    def _do_epoch_validate(self, ds_idx=1, dl=None):
        if dl is None: dl = self.dls[ds_idx]
        names = ['shuffle', 'drop_last']
        try:
            dl,old,has = change_attrs(dl, names, [False,False])
            self.dl = dl;                                    self('begin_validate')
            with torch.no_grad(): self.all_batches()
        except CancelValidException:       
```

**Comment by sgugger** [comment]
Oh this is from Jeremy, I did not know it was there. Since there are other safeguards with `get_preds` and `validate`, I'll remove.
