### ISSUE TITLE
AttributeError: can't set attribute

### ISSUE THREAD

**Issue by daniel-om-weber** [fastai/fastai2#29]
Calling databunch() on a Datasource leads to an AttributeError.
I did a fresh install from github of fastai2 and fastcore.

I reduced the code to the bare minimum required for execution:

from fastai2.basics import *
DataSource([0]*1000).databunch()

which leads to the following error

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-24-201140b923c5> in <module>
----> 1 DataSource([0]*1000).databunch()

~/miniconda3/lib/python3.7/site-packages/fastai2/data/core.py in databunch(self, bs, val_bs, shuffle_train, n, path, dl_type, dl_kwargs, **kwargs)
    153         if dl_type is None: dl_type = self._dl_type
    154         dls = [dl_type(self.subset(i), bs=b, shuffle=s, drop_last=s, n=n if i==0 else None, **kwargs, **dk)
--> 155                for i,(b,s,dk) in enumerate(zip(bss,shuffles,dl_kwargs))]
    156         return DataBunch(*dls, path=path)
    157 

~/miniconda3/lib/python3.7/site-packages/fastai2/data/core.py in <listcomp>(.0)
    153         if dl_type is None: dl_type = self._dl_type
    154         dls = [dl_type(self.subset(i), bs=b, shuffle=s, drop_last=s, n=n if i==0 else None, **kwargs, **dk)
--> 155                for i,(b,s,dk) in enumerate(zip(bss,shuffles,dl_kwargs))]
    156         return DataBunch(*dls, path=path)
    157 

~/miniconda3/lib/python3.7/site-packages/fastai2/data/core.py in __init__(self, dataset, bs, shuffle, num_workers, **kwargs)
     37         for nm in _batch_tfms:
     38             kwargs[nm] = Pipeline(kwargs.get(nm,None), as_item=(nm=='before_batch'))
---> 39         super().__init__(dataset, bs=bs, shuffle=shuffle, num_workers=num_workers, **kwargs)
     40         for nm in _batch_tfms: kwargs[nm].setup(self)
     41 

~/miniconda3/lib/python3.7/site-packages/fastcore/foundation.py in _init(self, *args, **kwargs)
    148                 if isinstance(arg,MethodType): arg = MethodType(arg.__func__, self)
    149                 setattr(self, k, arg)
--> 150         old_init(self, *args, **kwargs)
    151     functools.update_wrapper(_init, old_init)
    152     cls.__init__ = use_kwargs(cls._methods)(_init)

~/miniconda3/lib/python3.7/site-packages/fastai2/data/load.py in __init__(self, dataset, bs, num_workers, pin_memory, timeout, batch_size, shuffle, drop_last, indexed, n, device, **kwargs)
     73             try: n = len(dataset)
     74             except TypeError: pass
---> 75         store_attr(self, 'dataset,bs,shuffle,drop_last,indexed,n,pin_memory,timeout,device')
     76         self.rng,self.nw,self.offs = random.Random(),1,0
     77         self.fake_l = _FakeLoader(self, pin_memory, num_workers, timeout)

~/miniconda3/lib/python3.7/site-packages/fastcore/utils.py in store_attr(self, nms)
     74     "Store params named in comma-separated `nms` from calling context into attrs in `self`"
     75     mod = inspect.currentframe().f_back.f_locals
---> 76     for n in re.split(', *', nms): setattr(self,n,mod[n])
     77 
     78 #Cell

AttributeError: can't set attribute

**Comment by sgugger** [comment]
This has been fixed yesterday :)
