### ISSUE TITLE
Dependency errors

### ISSUE THREAD

**Issue by feribg** [fastai/fastai2#297]
The latest pip version 0.16 fails with:
https://github.com/fastai/fastai2/blob/cdb7bd914779fc0b5d4990e20b168745a2120305/fastai2/tabular/data.py#L14 `but` keyword undefined.

The latest repo version fails with:
```
NameError: name 'log_args' is not defined 
---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
<ipython-input-1-3b33610490f2> in <module>
     10 from tqdm import tqdm
     11 import torch.nn.functional as F
---> 12 from fastai2.data.all import *
     13 from fastai2.tabular.all import  *
     14 from fastai2.metrics import *

/workspace/fastai2/fastai2/data/all.py in <module>
----> 1 from ..torch_basics import *
      2 from .core import *
      3 from .load import *
      4 from .external import *
      5 from .transforms import *

/workspace/fastai2/fastai2/torch_basics.py in <module>
      3 from .torch_imports import *
      4 from .torch_core import *
----> 5 from .layers import *

/workspace/fastai2/fastai2/layers.py in <module>
    271 
    272 # Cell
--> 273 @log_args
    274 @funcs_kwargs
    275 class BaseLoss():

NameError: name 'log_args' is not defined
```

`0.0.13` is the only one that seems to work, but semi consistently  as `fit` intermittently fails with `fastprogress` conflict  (sometimes  works sometimes doesn't for the same code):
https://pastebin.com/MBdZTUMn

**Comment by borisdayma** [comment]
You need to install the latest version of fastcore (from git)

**Comment by feribg** [comment]
So fastcore from git, fastprogress from pip, and fastai1 and pytorch from conda? Can you confirm that's the correct recipe and I will opens PR for the docs.

**Comment by borisdayma** [comment]
It's actually already there: https://dev.fast.ai/

**Comment by feribg** [comment]
@borisdayma Still issue with both of fastai2 and fastcore installed from master.

<img width="1004" alt="Screen Shot 2020-04-14 at 2 09 03 PM" src="https://user-images.githubusercontent.com/1943817/79258754-a1cd5900-7e59-11ea-9b0e-8447f7dd0f8c.png">

**Comment by sgugger** [comment]
No this is a different issue, not an import problem anymore. Please open a new one with a reproducer if you want us to help.
