### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by daniel-om-weber** [fastai/fastai2#30]
Calling databunch() on a Datasource leads to an IndexError.
I did a fresh install from github of fastai2 and fastcore.

It does not matter what kind of iterable the Datasource contains.

from fastai2.basics import *
DataSource([0]*1000).databunch()

leads to the following error

---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
<ipython-input-8-42f5da8b34be> in <module>
      1 from fastai2.basics import *
----> 2 DataSource([0.]*1000).databunch()

~/miniconda3/lib/python3.7/site-packages/fastai2/data/core.py in databunch(self, bs, val_bs, shuffle_train, n, path, dl_type, dl_kwargs, **kwargs)
    149         if dl_type is None: dl_type = self._dl_type
    150         dls = [dl_type(self.subset(i), bs=b, shuffle=s, drop_last=s, n=n if i==0 else None, **kwargs, **dk)
--> 151                for i,(b,s,dk) in enumerate(zip(bss,shuffles,dl_kwargs))]
    152         return DataBunch(*dls, path=path)
    153 

~/miniconda3/lib/python3.7/site-packages/fastai2/data/core.py in <listcomp>(.0)
    149         if dl_type is None: dl_type = self._dl_type
    150         dls = [dl_type(self.subset(i), bs=b, shuffle=s, drop_last=s, n=n if i==0 else None, **kwargs, **dk)
--> 151                for i,(b,s,dk) in enumerate(zip(bss,shuffles,dl_kwargs))]
    152         return DataBunch(*dls, path=path)
    153 

~/miniconda3/lib/python3.7/site-packages/fastai2/data/core.py in __init__(self, dataset, bs, shuffle, num_workers, **kwargs)
     39         super().__init__(dataset, bs=bs, shuffle=shuffle, num_workers=num_workers, **kwargs)
     40         for nm in _batch_tfms: kwargs[nm].setup(self)
---> 41         if self.device is None: self._one_pass()
     42 
     43     def _one_pass(self):

~/miniconda3/lib/python3.7/site-packages/fastai2/data/core.py in _one_pass(self)
     42 
     43     def _one_pass(self):
---> 44         its = self.after_batch(self.do_batch([self.do_item(0)]))
     45         if self.device is None: self.device = find_device(its)
     46         self._n_inp = 1 if not isinstance(its, (list,tuple)) or len(its)==1 else len(its)-1

~/miniconda3/lib/python3.7/site-packages/fastai2/data/load.py in do_item(self, s)
    117     def prebatched(self): return self.bs is None
    118     def do_item(self, s):
--> 119         try: return self.after_item(self.create_item(s))
    120         except SkipItemException: return None
    121     def chunkify(self, b): return b if self.prebatched else chunked(b, self.bs, self.drop_last)

~/miniconda3/lib/python3.7/site-packages/fastai2/data/load.py in create_item(self, s)
    123     def randomize(self): self.rng = random.Random(self.rng.randint(0,2**32-1))
    124     def retain(self, res, b):  return retain_types(res, b[0] if is_listy(b) else b)
--> 125     def create_item(self, s):  return next(self.it) if s is None else self.dataset[s]
    126     def create_batch(self, b): return (fa_collate,fa_convert)[self.prebatched](b)
    127     def do_batch(self, b): return self.retain(self.create_batch(self.before_batch(b)), b)

~/miniconda3/lib/python3.7/site-packages/fastai2/data/core.py in __getitem__(self, it)
    203 
    204     def __getitem__(self, it):
--> 205         res = tuple([tl[it] for tl in self.tls])
    206         return res if is_indexer(it) else list(zip(*res))
    207 

~/miniconda3/lib/python3.7/site-packages/fastai2/data/core.py in <listcomp>(.0)
    203 
    204     def __getitem__(self, it):
--> 205         res = tuple([tl[it] for tl in self.tls])
    206         return res if is_indexer(it) else list(zip(*res))
    207 

~/miniconda3/lib/python3.7/site-packages/fastai2/data/core.py in __getitem__(self, idx)
    178 
    179     def __getitem__(self, idx):
--> 180         res = super().__getitem__(idx)
    181         if self._after_item is None: return res
    182         return self._after_item(res) if is_indexer(idx) else res.map(self._after_item)

~/miniconda3/lib/python3.7/site-packages/fastcore/foundation.py in __getitem__(self, idx)
    314     def _xtra(self): return None
    315     def _new(self, items, *args, **kwargs): return type(self)(items, *args, use_list=None, **kwargs)
--> 316     def __getitem__(self, idx): return self._get(idx) if is_indexer(idx) else L(self._get(idx), use_list=None)
    317     def copy(self): return self._new(self.items.copy())
    318 

~/miniconda3/lib/python3.7/site-packages/fastcore/foundation.py in _get(self, i)
    318 
    319     def _get(self, i):
--> 320         if is_indexer(i) or isinstance(i,slice): return getattr(self.items,'iloc',self.items)[i]
    321         i = mask2idxs(i)
    322         return (self.items.iloc[list(i)] if hasattr(self.items,'iloc')

IndexError: list index out of range

**Comment by sgugger** [comment]
Good catch, should be fixed now!
