### ISSUE TITLE
TabularPandas not working in 0.0.17

### ISSUE THREAD

**Issue by feribg** [fastai/fastai2#304]
Moving #297 as a separate item.

The following works in 0.0.13 and doesn't  in current master (0.0.17),  which seems to be the suggested approach here: https://dev.fast.ai/tabular.core

```
test = np.random.randn(1000,4)
test_df = pd.DataFrame(test, columns=['x1','x2','x3','y'])
splits = RandomSplitter(valid_pct=0.1)(range_of(test_df))
to = TabularPandas(test_df, [], None, ['x1','x2','x3'], y_names='y', splits=splits,)
dls = to.dataloaders(bs=256)
dls.valid.show_batch()
```

The following which is in the beginner tutorial fails with the same error:
```
dls = TabularDataLoaders.from_df(test_df, '.', [], None,['x1','x2','x3'], y_names='y', splits=splits,bs=256)
dls.valid.show_batch()
```

Stack :
https://pastebin.com/76JBZMFH

**Comment by sgugger** [comment]
Thanks for flagging, should be fixed now :)

**Comment by feribg** [comment]
thanks for  the quick fix
