### ISSUE TITLE
Removal of .fastai Directory Sometimes Needed

### ISSUE THREAD

**Issue by BSalita** [fastai/fastai2#305]
I've discovered some errors which were resolved by removing .fastai directory. The issues were discovered running course_v4 01_intro.ipynb in docker but aren't limited to either. I believe the errors can be mitigated by some software fix, improved error messaging or documentation.

Removing .fastai directory resolved the following errors:
1.  "CUDA out of memory error"
2. "list index out of range" when data loading, probably due to a defective cache.

Both issues were resolved by executing:
    rm -rf $HOME/.fastai

In the case of CUDA out of memory, perhaps the error message can suggest removal of .fastai as a possible solution. Also needs documenting, perhaps in a FAQ too.

In the case of "list index out of range", perhaps a sanity check needs implementing which verifies that the cache is valid. Also needs documenting, perhaps in a FAQ too.

I'll post both issues to the forum.

**Comment by sgugger** [comment]
CUDA out of memory means you have no memory on the GPU you are using. It needs a restart of the kernel, removing the .fastai directory will have no effect on that.

> "list index out of range" when data loading, probably due to a defective cache. 

is very vague and there is little we can do to see where this error came from without the full stack trace and (ideally) a reproducer.

Wiping the .fastai folder only removes the data and forces you to redownload it. It will not solve any issue you have in the code.
