### ISSUE TITLE
dls.test_dl doesn't work for tabular datasets

### ISSUE THREAD

**Issue by feribg** [fastai/fastai2#306]
The following code fails and when digging into the  values behind each  dataloader they aren't the same:

```
test = np.random.randn(1000,4)
test_df = pd.DataFrame(test, columns=['x1','x2','x3','y'])
test_df_clone = test_df.copy()
procs = [NormalizeTab]
splits = RandomSplitter(valid_pct=0.1, seed=3)(range_of(test_df))
to = TabularPandas(test_df, procs, None, ['x1','x2','x3'], y_names=['y'], splits=splits)
dls = to.dataloaders(bs=10)
test_dl = dls.test_dl(test_df_clone.loc[dls.valid.items.index],bs=10)
```

Error:
```
dls.valid.one_batch()
test_dl.one_batch()
```

Not matching:
```
dls.valid.items.head()
	x1|	x2|	x3|	y|
-------------------------------------------------
986	|-0.352882|	-0.886094|	0.783776|	-1.258688|
114	|-0.266398|	0.864658|	1.278003|	0.189900|
871	|0.262306|	-0.210300|	0.316592|	0.828911|
894	|-1.141342|	-3.085093|	0.314313|	-0.741556|
140	|0.477520|	0.403395|	-0.932348|	0.374099|
```

```
test_dl.head()
	x1	x2|	x3|	y|
---------------------------------------------------
986|	-0.288676|	-0.894359|	0.710076|	-1.258688|
114	|-0.203567|	0.852296|	1.167200	|0.189900|
871|	0.316730	|-0.220146|	0.277964|	0.828911|
894|	-1.064597|	-3.088210|	0.275856|	-0.741556|
140	|0.528522|	0.392113|	-0.877215|	0.374099|
```

**Comment by sgugger** [comment]
Please give a simple reproducer that tell us clearly what the problem is (and please copy the code and put in ```, a screenshot is not very useful for copy-paste).

I don't understand what your problem is from what you just stated, as I don't know which `proc` you passed, what are your `cat_names` and `cont_names`.

In general, you should not use `learn.dls.valid_ds.items` to pas to `test_dl` as it has been changed compared to your original dataframe (the processors have been applied to it). As shown in the [tabular tutorial](http://dev.fast.ai/tutorial.tabular), you should pass a copy of your original dataframe (for testing) or your new inference dataframe.

**Comment by feribg** [comment]
I  updated  to show the exact issue. It should be much clearer, sorry about the initial one.

**Comment by sgugger** [comment]
Thanks, this is clearer now. I'll look into this when I have some time.

**Comment by sgugger** [comment]
Are you sure you have the latest fastai2 and fastcore? I tried to reproduce but didn't manage.

**Comment by feribg** [comment]
Installed new env from scratch and cannot reproduce anymore. Anything special to clean up when installing from source?

**Comment by sgugger** [comment]
I think in this case it's just your fastcore that was out of date. Make sure you always update both together.
