### ISSUE TITLE
fit pretty table

### ISSUE THREAD

**Issue by lgvaz** [fastai/fastai2#308]
I'm not sure this is a bug, I just want to tag it to make sure this is the expected behavior.  

If we only use the `from fastai2.basics import *` to create a learner the fit function does not print a pretty table:
![image](https://user-images.githubusercontent.com/16520544/79510036-02ec5c80-8013-11ea-9ee6-8cbe4788090d.png)

For fixing the issue we also need to import the callbacks: `from fastai2.callback.all import *`

**Comment by sgugger** [comment]
Yes that is intended. People don't have the progress bars by default if they don't import the callback.
