### ISSUE TITLE
migrating notebook missing imports from fastai2.optimizer

### ISSUE THREAD

**Issue by sheikmohdimran** [fastai/fastai2#32]
In the notebook - migrating.ipynb, under section **'Use the fastai training loop'**, Adam is used in the Learner declaration without importing it from fastai2.optimizer

Current
```
data = DataBunch(train_loader, test_loader).cuda()
learn = Learner(data, Net(), loss_func=F.nll_loss, opt_func=Adam, metrics=accuracy)
```

To be changed to:
```
from fastai2.optimizer import Adam
data = DataBunch(train_loader, test_loader).cuda()
learn = Learner(data, Net(), loss_func=F.nll_loss, opt_func=Adam, metrics=accuracy)
```

**Comment by sgugger** [comment]
It is being imported by the first cell `from fastai2.basics import *` (basics contains the data submodule, learner, metrics and optimizers).
