### ISSUE TITLE
`RandTransform` never executes `encodes`

### ISSUE THREAD

**Issue by flpeters** [fastai/fastai2#321]
I tried using the `FlipItem` Transform from the vision module, which inherits from `RandTransform`, but no matter what I set `p` to, the flip never happens. I thought is was an issue with the Type, but even when defining a custom Transform without type dispatching, it still doesn't work.
Here's an example of what I tried:

```python
class RandTfm(RandTransform):
    def __init__(self, p=.5): self.p = p
    def encodes(self, o):
        print('flip')

t = RandTfm()

t(1)
```

That should print out 'flip' about 50% of the time. When calling `t.encodes(1)` directly, the print works, but just using `t(1)` doesn't.

Writing my own flip transform works:
```python
class RFlip(Transform):
    def __init__(self, flip_p=.5): self.flip_p = flip_p
    def encodes(self, o:(Image.Image,*TensorTypes)):
        if (random.random() < self.flip_p):
            print('flip')
            return PILImage(o.flip_lr())
        else: return o
```
but changing it to 
```python
class RFlip(RandTransform):
    def __init__(self, flip_p=.5): self.p = self.flip_p = flip_p
    def encodes(self, o:(Image.Image,*TensorTypes)):
        if (random.random() < self.flip_p):
            print('flip')
            return PILImage(o.flip_lr())
        else: return o
```
breaks it again (the above probablity should be 25%, but even after like 100 trials it never flipped).

**Comment by sgugger** [comment]
You need to pass `split_idx=0` to make the transform believe it is being applied on the training set, otherwise, it does nothing (as expected).

**Comment by flpeters** [comment]
Ah, I see, thank you for your help. That behavior is indeed mentioned in the notebook where `RandTransform` is defined.
I was following the `fastai2/nbs/10_tutorial.pets.ipynb` tutorial, where a `Pipeline` is defined as `tfms = Pipeline([Resize(224), PetTfm(), FlipItem(p=1), ToTensor()])`. Looks like that one is missing the `split_idx=0` as well then?

**Comment by sgugger** [comment]
Those are not new random transforms. This behavior is shown at the end of that tutorial, in the [segmentation section](http://dev.fast.ai/tutorial.pets#Segmentation).
