### ISSUE TITLE
DataLoader sampler

### ISSUE THREAD

**Issue by davecoates** [fastai/fastai2#33]
Is there a currently supported way of specifying a sampler to a data loader?

In https://github.com/fastai/fastai2/blame/c7e1c48c448e03491a34bf143cb3c5c969219781/nbs/examples/train_wt2.py#L32 it passes `sampler` to `TfmdDL` but this appears to be ignored entirely (at least in current master).

Or is the approach to achieving this different in fastai2? In my case I want to balance an unbalanced class dataset in the sampler

Thanks!

**Comment by davecoates** [comment]
Ah I think I better understand it now - have gone with approach similar to this: https://github.com/fastai/fastai2/blob/e0e387d7dd38b77b4bf39edb1c1d10cc1162a567/fastai2/callback/data.py#L16

Seems to work fine 👍

**Comment by tumbleintoyourheart** [comment]
Hi @davecoates. How do you use `WeightedDL`, with `DataBlock` or something?

**Comment by davecoates** [comment]
@tumbleintoyourheart I'm just using it with `DataBunch`

```
train_dl = BalancedTfmdl(
    train_ds,
    bs=bs,
    shuffle=True,
    after_batch=tfms,
)
valid_dl = BalancedTfmdl(
    valid_ds,
    bs=bs,
    after_batch=tfms,
)
data = DataBunch(train_dl, valid_dl)
```

**Comment by tumbleintoyourheart** [comment]
@davecoates thank you.
