### ISSUE TITLE
Too broad data/ in .gitignore

### ISSUE THREAD

**Issue by indigoviolet** [fastai/fastai2#332]
I think this was unintentional:

https://github.com/fastai/fastai2/blob/e397c548ecb0200be17ee621533b2589d8910df3/.gitignore#L2

It causes files in `fastai2/data` to be git-ignored (but that is the `fastai2.data` package!)

```
➜ touch fastai2/data/foo     
➜ git status --ignored       
On branch master
Your branch is up to date with 'origin/master'.

Ignored files:
  (use "git add -f <file>..." to include in what will be committed)

        fastai2/data/foo

nothing to commit, working tree clean
```

**Comment by sgugger** [comment]
Yes this comes from fastai (v1) and is definitely unintentional. Thanks for flagging!
