### ISSUE TITLE
XSENet family

### ISSUE THREAD

**Issue by tumbleintoyourheart** [fastai/fastai2#34]
Hi.

I noticed that XSENet family have been in `https://github.com/fastai/fastai2/blob/bb49c1794b82271cd61ae19287a1e7430559bb97/fastai2/vision/models/xresnet.py#L95` for quite a while.
Will they be ready to use in any soon?

**Comment by sgugger** [comment]
What do you mean by ready to use? You can use them right now. There is no pretrained model associated however (the arch is not defined the same way so you'll need to get them from another source).

**Comment by tumbleintoyourheart** [comment]
> What do you mean by ready to use? You can use them right now. There is no pretrained model associated however (the arch is not defined the same way so you'll need to get them from another source).

I mean when init a model in the family, it gives an error `NameError: name 'XSENet' is not defined`. And I know that there's no pretrained yet.

**Comment by sgugger** [comment]
Yes there is no class XSENet. This is all defined using the generic XResNet class. You have a wide list of functions for different xse resnet, look at the [source notebook](https://github.com/fastai/fastai2/blob/master/nbs/11_vision.models.xresnet.ipynb) for more details.

**Comment by tumbleintoyourheart** [comment]
Sorry but I haven't understood yet. Yes we have several choice of xse_resnet made out of XResNet class, but from [xsenet154](https://github.com/fastai/fastai2/blob/bb49c1794b82271cd61ae19287a1e7430559bb97/fastai2/vision/models/xresnet.py#L93) defined by `SENet(SEBlock, g3, groups=64, reduction=16, p=0.2, c_out=c_out)` and xse_resnext define by `return XSENet(SEResNeXtBlock`. I didn't find any source for `SENet` and `XSENet`.

**Comment by sgugger** [comment]
Oh I think this is a typo, it should be XResNet everywhere, will fix.

**Comment by tumbleintoyourheart** [comment]
Thank you.
