### ISSUE TITLE
size of the pkl file created by learn.export() vs batch size

### ISSUE THREAD

**Issue by piegu** [fastai/fastai2#350]
Hello,

UNB colleagues (Brasilia, Brazil) and I noticed and tested (see my note at the bottom of this message) that the size of the pkl file created by [learn.export()](https://github.com/fastai/fastai2/blob/master/fastai2/learner.py#L500) depends on the batch size (at least in my test, it depends on large batch size).

I posted this comment on the [fastai forum](https://forums.fast.ai/) and @sgugger already [replied](https://forums.fast.ai/t/issue-with-learn-export/67725/15) to me saying:

> It’s probably because the .xb .yb and .pred that contain the last batch (inputs, target, predictions) are saved with the Learner.

Sylvain is currently busy with the fastai book and will be able to verify this only afterwards. In order not to forget it, I open this issue in the fastai v2 github.

Note: my [notebook](https://github.com/piegu/fastai-projects/blob/master/learn_export_files_by_batchsize_fastaiv2.ipynb) is online in github and the following table shows my results (sizes of pkl files by batch size from 8 to 512). The smallest pkl file (bs from 8 to 128) has a size of 52M and the biggest (bs of 512) of 272M.

![image](https://user-images.githubusercontent.com/20000948/81804218-23fb7c80-94ef-11ea-9598-515ad4b4436b.png)

**Comment by sgugger** [comment]
I have pushed a fix (I think). Please reopen if it did not solve the issue.

**Comment by piegu** [comment]
Hello Sylvain. 

In my ubuntu installation of fastai2, I ran `git pull` to get the updated files you changed and I got them.

After I ran again my [notebook](https://github.com/piegu/fastai-projects/blob/master/learn_export_files_by_batchsize_fastaiv2.ipynb) about batch size vs `learn.export()` pkl file and there was no change: 

- bs = 512 | export.pkl = 285 MB
- bs = 8 | export.pkl = 54.2 MB

Therefore, I re-opened this [issue](https://github.com/fastai/fastai2/issues/350).
