### ISSUE TITLE
`plot_top_losses` not showing for Tabular data

### ISSUE THREAD

**Issue by muellerzr** [fastai/fastai2#351]
Currently `plot_top_losses` when working with tabular won't return anything. The reason is `its` is `None`, so it skips the `plot_top_losses` argument. What's happening is when we call `_pre_show_batch`, only `x1` is returned, nothing for `y1` and `outs`

To recreate, run Adults and then attempt `plot_top_losses`. Line by line I found this on the first call here:
```python
x,y,its = self.dl._pre_show_batch(b, max_n=k)
```
Which then of course compounds when we try calling `_pre_show_batch` later

**Comment by sgugger** [comment]
Yes, there is nothing implemented for the full batch case (like tabular) yet. Will look into it when I have time.

**Comment by muellerzr** [comment]
Thanks!
