### ISSUE TITLE
for tutorial.siamese, why 'concat' the two encoder output instead of one minus the other?

### ISSUE THREAD

**Issue by yijinlee** [fastai/fastai2#357]
Hi.

Just wondering why the [tutorial.siamese](https://github.com/fastai/fastai2/blob/master/nbs/24_tutorial.siamese.ipynb) notebook concats the two encoder output, instead of taking one minus the other (which seems to be the usual practice for Siamese network)?

```python
ftrs = torch.cat([self.encoder1(x1), self.encoder2(x2)], dim=1)
```

Was it found to perform better empirically (e.g. because we have 2x trainable params coming out of encoders, ala fastai's typical 'ConcatPool'), and/or is there literature that shows 'concat' is better than 'take difference'?

One potential "downside" (if we could call it that) of doing 'concat' is that the prediction is not symmetrical for a pair of images, i.e. it is dependent on the order of the two images fed in, e.g. pseudocode predict(x[0],x[1]) gives different output to predict(x[1],x[0]). I guess one could do the two inferences (in the two image orders) and then take the average, but I am just wondering about the original motivation to do 'concat' to begin with.

Thoughts and comments much appreciated. Thanks!

**Comment by sgugger** [comment]
This should be asked on the [forum](https://forums.fast.ai/) since we keep the issues for bugs in the library only :)
It's concatenated because I tried that and didn't know that difference was the usual thing. Feel free to experiment with it and report back on the forum, we can then change to what works best!

**Comment by yijinlee** [comment]
Thanks for your reply. I'll have a play around and then report back. Will send a pull request for the notebook if there is anything worth adding/noting : )
