### ISSUE TITLE
AWD_LSTM crash google colab session when put on 'cuda'

### ISSUE THREAD

**Issue by tumbleintoyourheart** [fastai/fastai2#360]
The code bellow, taken from [AWD_LSTM docs](http://dev.fast.ai/text.models.awdlstm#AWD_LSTM) with  additional `.cuda()` crashes google colab sessions.
```
tst = AWD_LSTM(100, 20, 10, 2).cuda()
x = torch.randint(0, 100, (10,5)).cuda()
```
Some says it has to do with some inner tensors of the model which were not put on 'cuda' properly. How does fastai2 handle this when using AWD_LSTM in a Text Learner for example? Thanks.

**Comment by sgugger** [comment]
It works perfectly on my side (without using colab). What's the error exactly? And the fastaid version used?

**Comment by tumbleintoyourheart** [comment]
I used fastai2 version 0.0.17. And the error is that Colab just threw a crash session message, every trial of it. I managed to make it run temporarily by adding `.to(device)` to the every inner tensors (3 in total) in `_one_hidden` `_change_one_hidden` methods.
So if it works ok on your side then it would be a Colab's own issue. I think this should be closed.
