### ISSUE TITLE
About the usage for multivariate time series problem

### ISSUE THREAD

**Issue by kaiyunpan** [fastai/fastai2#365]
Hello,

I am new to time series classification and I want to apply your developed software. One question I had after testing your code, is whether is possible to do multivariate time series classification using your code? If so, how could I formulate the data into pandas DataFrame to put it as df_train? 
Thanks for your help.

Best regards,
Kaiyun

**Comment by sgugger** [comment]
Hi there, we use issues for standing bugs only. You should ask your question on the [forum](https://forums.fast.ai/), you're more likely to get an answer to it there.
