### ISSUE TITLE
Larger batch sizes for variable image input

### ISSUE THREAD

**Issue by syb0rg** [fastai/fastai2#367]
I have a large dataset of variably sized images I can train with using the following:

```
learn = Learner(dls,
                Model(), 
                loss_func=CrossEntropyLossFlat(axis=-1),
                metrics=[accuracy]).to_fp16()
learn.fit_flat_cos(8, 1e-4)
```

This will only work if the batch size is 1.  When I try increasing the batch size to anything greater than this, I get these errors:

> RuntimeError: stack expects each tensor to be equal size, but got [3, 552, 461] at entry 0 and [3, 682, 192] at entry 1

For my purposes, resizing or cropping are not possible; hence I've made my model handle it.  If I pad all the images to match the largest dimensions, there are some very large samples and I will end up with multiple megapixels of wasted space.  Is there a viable way for me to increase the batch size (GPU memory allowing)?

**Comment by sgugger** [comment]
Please use the [forum](https://forums.fast.ai/) for these questions as we use the issues for bugs only. If you don't resize your images to the same size, you can't batch them, no.

**Comment by syb0rg** [comment]
I thought this was possible in previous versions of fastai?  Where it would dynamically pad a batch so the sizes matched?  If so I would think this is a bug, if not then yeah this would be more of a feature request.
