### ISSUE TITLE
Some broken links in generated docs

### ISSUE THREAD

**Issue by tyoc213** [fastai/fastai2#374]
I guess there are others than this ones

* 2 links broken from doc http://dev.fast.ai/learner#load_learner load_learner and Learner
* at the end of https://dev.fast.ai/tabular.learner the link to https://dev.fast.ai/13a_learner#Learner

**Comment by sgugger** [comment]
This is actually an issue with a regex in nbdev. Will try to fix.

**Comment by sgugger** [comment]
This has been fixed by [this commit in nbdev](https://github.com/fastai/nbdev/commit/c8729bbcf1ed8ca31ee4d16c33935b5f44b74997) and a new doc generation here.
