### ISSUE TITLE
Issue about issues

### ISSUE THREAD

**Issue by tcapelle** [fastai/fastai2#390]
Just checking if Sylvain is still around...
Probably he is fixing issues now @huggingface
Congratz on your new job, are you bringing fastai2 to the table?

**Comment by sgugger** [comment]
I'm still looking when I have a bit of time, but I won't be a main maintainer either. As for HuggingFace, no plan for more integration in fastai v2 on my side no. They do provide data and a model that you can pass to a `Learner` and train with fastai.

**Comment by tcapelle** [comment]
Super, are you working remotely or with the team at NY?

**Comment by sgugger** [comment]
Remotely because of the pandemic, but I'm based in NY so will join the NY office when it's safe.
