### ISSUE TITLE
Running into error when attempting to import from fastai2

### ISSUE THREAD

**Issue by MakarDevushkin** [fastai/fastai2#398]
I run into the following error when attempting to import from fastai2.vision.all. Have already updated my PIL version as suggested in a previous thread.

<img width="995" alt="Screen Shot 2020-06-14 at 3 00 05 PM" src="https://user-images.githubusercontent.com/46318534/84587274-4404bf80-ae50-11ea-9f2a-ca479e32a233.png">

**Comment by muellerzr** [comment]
What is the PILLOW version running? And did you restart the kernel after upgrading?

**Comment by MakarDevushkin** [comment]
I have restarted to no avail. My PILLOW version is 7.1.2

**Comment by mikonapoli** [comment]
What version of fastai2 are you using? Trying pulling and reinstalling. I suspec you are missing this
```
Signature: Image.Image.size.fget(x: PIL.Image.Image)

    @patch_property
    def size(x:Image.Image): return Tuple(_old_sz(x))
```
