### ISSUE TITLE
_merge_tfms swallows lambda functions

### ISSUE THREAD

**Issue by slawekslex** [fastai/fastai2#399]
While removing duplicates the `_merge_tfms` function will also remove all but one lambda functions even if they do different things. For example:
```
f1 = lambda x: x+20
f2 = lambda x: x+3
Pipeline(_merge_tfms([f1,f2]))(1)
4
```
I run into this by having different `TransformBlocks` which used lambdas and they get merged by `DataBlock`

**Comment by mikonapoli** [comment]
Where is the `_merge_tfms` coming from?

**Comment by slawekslex** [comment]
https://github.com/fastai/fastai2/blob/bf455de9bc37c76f7f92b3c43227ef9d4779b614/fastai2/data/block.py#L41

**Comment by jph00** [comment]
Thanks - fixed in master.
