### ISSUE TITLE
PILDicom fails to load an image

### ISSUE THREAD

**Issue by Apollo-XI** [fastai/fastai2#404]
PILDicom fails to load a Dicom file if you don't pass a Path or bytes when it should accept strings. See [this post](https://forums.fast.ai/t/dataloader-error-with-dicom-files/73559). It fails because none of the ifs are valid and the try to do `im.load` (see code below). I think that  
`if isinstance(fn,Path)` should be `if isinstance(fn,(Path, str))` + dcmread should accept strings

```
@patch
def dcmread(fn:(str, Path), force = False): # <- add str type
    "Open a `DICOM` file"
    return pydicom.dcmread(str(fn), force)

class PILDicom(PILBase):
    _open_args,_tensor_cls,_show_args = {},TensorDicom,TensorDicom._show_args
    @classmethod
    def create(cls, fn:(Path,str,bytes), mode=None)->None:
        "Open a `DICOM file` from path `fn` or bytes `fn` and load it as a `PIL Image`"
        if isinstance(fn,bytes): im = Image.fromarray(pydicom.dcmread(pydicom.filebase.DicomBytesIO(fn)).pixel_array)
        if isinstance(fn,(str, Path)): im = Image.fromarray(dcmread(fn).pixel_array) # <- Change the if
        im.load() 
        im = im._new(im.im)
        return cls(im.convert(mode) if mode else im)
```

Finally, it would be nice if some kind of message is given to the user if pass a not supported type.

**Comment by jph00** [comment]
Makes sense - will fix. Thanks.
