### ISSUE TITLE
show_images does not have a cmap option

### ISSUE THREAD

**Issue by asvcode** [fastai/fastai2#407]
Currently the `show_images` function does not have an option to specify cmap colors.  When dealing with some DICOM datasets it would be good to specify a cmap color.  This works fine when using `show_image` but not when using `show_images`

Currently:
```
@delegates(subplots)
def show_images(ims, nrows=1, ncols=None, titles=None, **kwargs):
    "Show all images `ims` as subplots with `rows` using `titles`"
    if ncols is None: ncols = int(math.ceil(len(ims)/nrows))
    if titles is None: titles = [None]*len(ims)
    axs = subplots(nrows, ncols, **kwargs)[1].flat
    for im,t,ax in zip(ims, titles, axs): show_image(im, ax=ax, title=t)
```
Changing it to:
```@delegates(subplots)
def show_images(ims, nrows=1, ncols=None, titles=None, cmap=None, **kwargs):
    "Show all images `ims` as subplots with `rows` using `titles` and specify a cmap color if needed"
    if ncols is None: ncols = int(math.ceil(len(ims)/nrows))
    if titles is None: titles = [None]*len(ims)
    axs = subplots(nrows, ncols, **kwargs)[1].flat
    for im,t,ax in zip(ims, titles, axs): show_image(im, ax=ax, title=t, cmap=cmap)```

solves the issue, happy to submit a PR if appropriate

**Comment by slawekslex** [comment]
Not sure if you are already aware of that, but you can set display args on your tensor type and that's used when you do show_batch etc. For example the definition of TensorDicom already is:
```class TensorDicom(TensorImage): _show_args = {'cmap':'gray'}```

**Comment by asvcode** [comment]
@slawekslex Thanks for your suggestion, that would work!  Your suggestion made me think and a better option would be to set the  `cmap` selection like so (which works):

`matplotlib.rcParams['image.cmap'] = 'ocean'`

This way it would set the `cmap` selection for the whole notebook, however it would still be nice to have the option to select individual `cmap` selections for each `show_images` so you can compare what different colors.

**Comment by Kshitij09** [comment]
> class TensorDicom(TensorImage): _show_args = {'cmap':'gray'}

I'd like to add to this answer. You can update the cmap for a class as follows:
```python
TensorDicom._show_args['cmap'] = 'ocean'
```

But yes, I totally agree with making a provision to customize `show_image` behavior. Something like [unet_config](https://github.com/fastai/fastai2/blob/2c9cb629c436731352fce0ebfe3dcf3e6d6b87a3/fastai2/vision/learner.py#L182) would work in this case.
