### ISSUE TITLE
`show` function does not take into consideration DICOM images that have more than 1 frame

### ISSUE THREAD

**Issue by asvcode** [fastai/fastai2#408]
Most `.dcm` datasets have 1 frame per file but some datasets have more than 1 frame per `.dcm` file.   In this case the `show` function fails with a `type` error:

![typeerror](https://user-images.githubusercontent.com/25020209/85318693-48932e80-b475-11ea-8748-92eb9ebd37cb.PNG)

Current code:
```
@patch
@delegates(show_image)
def show(self:DcmDataset, scale=True, cmap=plt.cm.bone, min_px=-1100, max_px=None, **kwargs):
    px = (self.windowed(*scale) if isinstance(scale,tuple)
          else self.hist_scaled(min_px=min_px,max_px=max_px,brks=scale) if isinstance(scale,(ndarray,Tensor))
          else self.hist_scaled(min_px=min_px,max_px=max_px) if scale
          else self.scaled_px)
    show_image(px, cmap=cmap, **kwargs)
```

Updating the code:
-  to include checking for the number of `ndims` 
- specify how many frames to view (default set at 1)

```
@patch
@delegates(show_image, show_images)
def show(self:DcmDataset, frames=1, scale=True, cmap=plt.cm.bone, min_px=-1100, max_px=None, **kwargs):
    px = (self.windowed(*scale) if isinstance(scale,tuple)
          else self.hist_scaled(min_px=min_px,max_px=max_px,brks=scale) if isinstance(scale,(ndarray,Tensor))
          else self.hist_scaled(min_px=min_px,max_px=max_px) if scale
          else self.scaled_px)
    if px.ndim > 2: 
        gh=[]
        p = px.shape; print(f'{p[0]} frames per file')
        for i in range(frames): u = px[i]; gh.append(u)
        show_images(gh, cmap=cmap, **kwargs)    
    else: 
        print('1 frame per file')
        show_image(px, cmap=cmap, **kwargs)
```

With the update if the dataset only has 1 image per file:
![one_p](https://user-images.githubusercontent.com/25020209/85318932-aaec2f00-b475-11ea-9b29-699fb2d15a8f.PNG)

However if a dataset has more than 1 frame per file: can specify number of frames to view and with reported issue [407](https://github.com/fastai/fastai2/issues/407) specify cmap color

![two_p](https://user-images.githubusercontent.com/25020209/85319349-38c81a00-b476-11ea-8ccc-ffd22f6fc18f.PNG)

**Comment by jph00** [comment]
Thanks for noting this - feel free to submit a PR with that fix.

**Comment by asvcode** [comment]
Thanks Jeremy, will work on the PR.
