### ISSUE TITLE
RandTransform before_call doesn't respect TypeDispatch

### ISSUE THREAD

**Issue by slawekslex** [fastai/fastai2#409]
See the code:
```
class TA(TensorBase):pass

class T(RandTransform):
    def before_call(self, x, split_idx):
        print('before_call', x)
        self.do = True
        self.split_idx = None
    
    def encodes(self, x:TA):
        print('encodes', x)
        return x + 42
    
x = (tensor(2), TA(tensor(3)))
T()(x)
```
```
before_call (tensor(2), TA(3))
encodes TA(3)
```

The input to `before_call` is the whole tuple, rather than the element we apply the transform to.

The concrete example of when this causes a problem is using RandomResizedCrop when the image is at a position other than 0, it will try to get the size of whatever is at the index 0, rather than the image.

**Comment by mikonapoli** [comment]
That would be because you are saving the tuple into a variable and then passing the variable, i.e. the whole tuple. If I understood what you want to achieve, you should unpack the tuple by calling `T()(*x)`

which yields 
```
before_call tensor(2)
tensor(2)
```

**Comment by slawekslex** [comment]
This was just a toy example of the problem, in the real world I don't invoke the transform directly (a `Pipeline` inside `TfmdDL` does).

Transforms do operate on whole tuples, the code [here](https://github.com/fastai/fastcore/blob/4a2d5ea702d0dc4a6c34c4acefafd9b494d9e222/fastcore/transform.py#L87) is responsible for breaking down a tuple into individual items and using `TypeDispatch` to pass it to appropriate `encode` methods. The issue here is that the `before_call` doesn't adhere to that logic.

**Comment by jph00** [comment]
Thanks for mentioning this, @slawekslex . `before_call` actually relies on having access to a tuple. Quite a few of the tests check for this behavior, and it's needed for stuff like handling the combination of tensor points and an image. Would you be able to create a new issue showing an example of, e.g. "using RandomResizedCrop when the image is at a position other than 0".
