### ISSUE TITLE
TypeError: setup() takes from 1 to 2 positional arguments but 3 were given

### ISSUE THREAD

**Issue by mrT23** [fastai/fastai2#41]
i updated fastai and fastcore to latest version (9/1/2020), and got the following error:

`  File "...\fastcore\foundation.py", line 41, in __call__
    res = super().__call__(*((x,) + args), **kwargs)
  File "...\fastai2\data\core.py", line 175, in __init__
    if do_setup: self.setup(train_setup=train_setup)
  File "...fastai2\data\core.py", line 188, in setup
    self.tfms.setup(self, train_setup)
TypeError: setup() takes from 1 to 2 positional arguments but 3 were given`

**Comment by jdiedrick** [comment]
@mrT23 I think fastcore is out of sync (latest is 0.9.1 but the updates to the codebase in question aren't reflected in that release.) . Doing an editable install of both got it working for me

**Comment by mrT23** [comment]
thanks @jdiedrick , it solved the problem!
