### ISSUE TITLE
TensorImage show() raises RuntimeError: number of dims don't match in permute

### ISSUE THREAD

**Issue by ibayer** [fastai/fastai2#413]
Hi,
thanks for this great library!
While playing with the **Bounding Boxes** section of `50_tutorial.datablock.ipynb`
I run into an error I couldn't resolve. I'm new to `@typedispatch` but from my current understanding I think
rendering an `TensorImage` with `.show()` should work.

```python
from fastai2.data.all import *
from fastai2.vision.all import *
from nbdev.showdoc import show_doc

coco_source = untar_data(URLs.COCO_TINY)
images, lbl_bbox = get_annotations(coco_source/'train.json')
img2bbox = dict(zip(images, lbl_bbox))

coco = DataBlock(blocks=(ImageBlock, BBoxBlock, BBoxLblBlock),
                 get_items=get_image_files,
                 splitter=RandomSplitter(),
                 get_y=[lambda o: img2bbox[o.name][0], lambda o: img2bbox[o.name][1]], 
#                  item_tfms=Resize(128),
                 batch_tfms=aug_transforms(),
                 n_inp=1)
dls = coco.dataloaders(coco_source, bs=1)
```

`dls.show_batch(max_n=9)` displays an nice image. However

`b[0].show()` throws:

```python
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-10-47db80168e01> in <module>
----> 1 b[0].show()

~/git/competitions/RoadDamage20/fastai2/fastai2/torch_core.py in show(self, ctx, **kwargs)
    296     _show_args = ArrayImageBase._show_args
    297     def show(self, ctx=None, **kwargs):
--> 298         return show_image(self, ctx=ctx, **{**self._show_args, **kwargs})
    299 
    300 # Cell

~/git/competitions/RoadDamage20/fastai2/fastai2/torch_core.py in show_image(im, ax, figsize, title, ctx, **kwargs)
     44     if hasattrs(im, ('data','cpu','permute')):
     45         im = im.data.cpu()
---> 46         if im.shape[0]<5: im=im.permute(1,2,0)
     47     elif not isinstance(im,np.ndarray): im=array(im)
     48     # Handle 1-channel images

RuntimeError: number of dims don't match in permute
```

Given that

```python
b = dls.one_batch()
type(b[0])
```
returns `fastai2.torch_core.TensorImage` I would expect that `b[0]` can be rendered with `.show()`.

I have run this on the latest version of master (bf455de9bc37c76f7f92b3c43227ef9d4779b614).

**Comment by mikonapoli** [comment]
No issue there:

when you are taking `b[0]` you are actually not getting a single image, but a batch of size one. And `show` expects to be called on an image (that's why it is complaining about `im=im.permute(1,2,0)`: it needs something of rank 3, but you are passing it a rank 4 tensor, which you can verify by running `b[0].shape`

When you call `show_batch`, the method first call `dls._pre_show_batch`, which will separate your rank 4 tensor into a list of rank 3 tensor (and other things) before calling `show` on each of those

**Comment by asvcode** [comment]
I agree with @mikonapoli 's answer that calling `b[0]` produces a rank 4 tensor (and hence the error) where the first value is the batch size.  If you did however want to view the images or image within this batch:

`show_images(b[0])` will show all images within the batch and

`show_image(b[0][0])` will show the first image within that batch

**Comment by ibayer** [comment]
Thanks for the clarification. I understand now that 

```
type(test_image)

fastai2.torch_core.TensorImage
```

tells me that test_image is a container `TensorImage` of images and that `show_image/s()` is able to, well
show image/s in container/tensor or individual images.

I guess what confuses me is that `TensorImage` has a function `show()` which doesn't work due to rank miss match and
individual element from `TensorImage` don't have a `show()` function.

I was under the impression that `TensorImage` should be able to render it self and without requiring an external function like `show_image/s` for this.

I'll close the issue in a few hours if there is an agreement that the current behavior is expected.

**Comment by ibayer** [comment]
`show()` works on a `TensorImage` with a single element but doesn't work with multiple elements.

![image](https://user-images.githubusercontent.com/1497140/86150033-1d57b180-bafd-11ea-97ef-8dd0146874f6.png)

The error in the first cell can be explained by  `TensorImage` to `tensor`  type conversion due to (`[0]`) indexing.
The error in the second cell seems to indicates that `.show()` fails for `TensorImage` with multiple images.

![image](https://user-images.githubusercontent.com/1497140/86150213-6445a700-bafd-11ea-9960-ab216b921e88.png)

**Comment by ibayer** [comment]
Closing since behavior seem to be expected.
