### ISSUE TITLE
AttributeError: type object 'Image' has no attribute 'size' in fastbook example notebook

### ISSUE THREAD

**Issue by sreejithmm** [fastai/fastai2#421]
Error while executing this cell
```
#id first_training
#caption Results from the first training
# CLICK ME
from fastai2.vision.all import *
path = untar_data(URLs.PETS)/'images'

def is_cat(x): return x[0].isupper()
dls = ImageDataLoaders.from_name_func(
    path, get_image_files(path), valid_pct=0.2, seed=42,
    label_func=is_cat, item_tfms=Resize(224))

learn = cnn_learner(dls, resnet34, metrics=error_rate)
learn.fine_tune(1)

```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-2-ea370ae96d6e> in <module>()
      2 #caption Results from the first training
      3 # CLICK ME
----> 4 from fastai2.vision.all import *
      5 path = untar_data(URLs.PETS)/'images'
      6 

/anaconda3/lib/python3.7/site-packages/fastai2/vision/all.py in <module>()
      1 from ..basics import *
----> 2 from ..callback.all import *
      3 from .augment import *
      4 from .core import *
      5 from .data import *

/anaconda3/lib/python3.7/site-packages/fastai2/callback/all.py in <module>()
      3 from .fp16 import *
      4 from .hook import *
----> 5 from .mixup import *
      6 from .progress import *
      7 from .schedule import *

/anaconda3/lib/python3.7/site-packages/fastai2/callback/mixup.py in <module>()
      6 from ..basics import *
      7 from .progress import *
----> 8 from ..vision.core import *
      9 
     10 from torch.distributions.beta import Beta

/anaconda3/lib/python3.7/site-packages/fastai2/vision/core.py in <module>()
     19 # Cell
     20 if not hasattr(Image,'_patched'):
---> 21     _old_sz = Image.Image.size.fget
     22     @patch_property
     23     def size(x:Image.Image): return Tuple(_old_sz(x))

AttributeError: type object 'Image' has no attribute 'size'

**Comment by sreejithmm** [comment]
why was this closed? I am still getting errors? Any help is appreciated

**Comment by sreejithmm** [comment]
ok,

for others ..this is becuase PIL version is outdated. My system had 5.2.0
requirements.txt didnt have this upgrade command. So manually install using below command

python3 -m pip install --upgrade Pillow

**Comment by jph00** [comment]
FYI it was closed because you should use the forums for help.
