### ISSUE TITLE
UserWarning: This overload of nonzero is deprecated: 	nonzero()

### ISSUE THREAD

**Issue by eugeneware** [fastai/fastai2#434]
I continually get this warning while training with the latest `fastai2` library and pytorch 1.6.0 and torchvision 0.7.0 and git commit 2b19225. Happens with the first first notebook in the `fastbook` repository.

![IMG_0582](https://user-images.githubusercontent.com/38154/88735865-d69cbc00-d17b-11ea-9dcb-1b6732165682.jpeg)

Here's the warning.

```
/home/fastai/fastai2/fastai2/callback/schedule.py:68: UserWarning: This overload of nonzero is deprecated:
	nonzero()
Consider using one of the following signatures instead:
	nonzero(*, bool as_tuple) (Triggered internally at  /opt/conda/conda-bld/pytorch_1595629427478/work/torch/csrc/utils/python_arg_parser.cpp:766.)
  idx = (pos >= pcts).nonzero().max()
```

**Comment by jph00** [comment]
Thanks!
