### ISSUE TITLE
sklearn's `matthews_corrcoef` doesn't really support multi-label, hence `MatthewsCorrCoefMulti` won't work

### ISSUE THREAD

**Issue by tianjianjiang** [fastai/fastai2#439]
```python
/usr/local/lib/python3.6/dist-packages/sklearn/metrics/_classification.py in matthews_corrcoef(y_true, y_pred, sample_weight)
    883     check_consistent_length(y_true, y_pred, sample_weight)
    884     if y_type not in {"binary", "multiclass"}:
--> 885         raise ValueError("%s is not supported" % y_type)
```

`ValueError: multilabel-indicator is not supported`

**Comment by jph00** [comment]
This isn't enough information for me to understand. Please provide a minimal reproducer, say what you expect to happen, and show what actually happened.

**Comment by tianjianjiang** [comment]
> This isn't enough information for me to understand. Please provide a minimal reproducer, say what you expect to happen, and show what actually happened.

My apologies for the trouble. Judging by the code of sklearn, there's no way it can do multi-label `matthews_corrcoef()`, therefore I didn't provide any reproducer. To be more specific:

1. `MatthewsCorrCoefMulti` uses `skm_to_fastai`
2. `skm_to_fastai` uses `skm.matthews_corrcoef`, i.e., `sklearn.metrics.matthews_corrcoef`
3. `sklearn.metrics.matthews_corrcoef` uses `y_type, y_true, y_pred = _check_targets(y_true, y_pred)`
4. `_check_targets` correctly detects `y_type` as `multilabel-indicator`
5. `sklearn.metrics.matthews_corrcoef` rejects `multilabel-indicator` @ https://github.com/scikit-learn/scikit-learn/blob/master/sklearn/metrics/_classification.py#L834

For your reference, I bumped into this when I was reproducing https://ohmeow.github.io/blurr/modeling-core/#Example:-Multi-label-classification with additional metrics including `MatthewsCorrCoefMulti`.

**Comment by jph00** [comment]
Thanks. So would your suggestion be for us to remove that function?

**Comment by danieldiamond** [comment]
Enjoyed following this turn of events:

It appears it was previously removed [here](https://github.com/fastai/fastai2/commit/4bde87b0a2144f6ad4e816ad4c2ab48628b911a7) -- there was a previous issue raised [here](https://github.com/fastai/fastai2/issues/155)

But then it was added again [here](https://github.com/fastai/fastai2/pull/384)

Making a new PR to remove it again (but getting stuck on [this issue](https://github.com/fastai/fastai2/issues/442) now - so will try recommend an appropriate solution for that issue first)

**Comment by tianjianjiang** [comment]
@jph00 @danieldiamond Ah, sorry for not investigating past issues. To my best knowledge, it is really hard to find papers/applications that actually used Matthew's Corr. Coef. to evaluate multi-label problems.

However, since we have multi-label versions of precision, recall, and f-measure, IMO it is possible to reuse their confusion matrix components to define a multi-label version of Matthew's Corr. Coef. I'm just not sure whether there's a nice way to vectorize them like sklearn did.

**Comment by jph00** [comment]
Thanks to you both! I'll go ahead and remove it. @danieldiamond see Zach's response on #442 to resolve the build issue.
