### ISSUE TITLE
nb2, download images

### ISSUE THREAD

**Issue by nikky4D** [fastai/fastai2#44]
In the lines in nbs, lesson2-download.ipynb:
`    print(c)
    file = f'urls_{c}.csv'
    download_images(path/file, path/c, max_pics=200)`

I believe this should have the file as 2nd input, and folder as first input. It works in my google colab using current fastai2. 

Another question: how do I find the function: download_images in github?

**Comment by sgugger** [comment]
Good catch, I will fix this.
`https://github.com/fastai/fastai2/blob/32fa0374b12810346399e4e6e9f9e451480ece46/fastai2/vision/utils.py#L19`. In colab, you can just do
```
from nbdev.showdoc import *
show_doc(download_images)
```
to see the documentation and get a link to the source.
