### ISSUE TITLE
Moving docs raising issues with nbdev package

### ISSUE THREAD

**Issue by danieldiamond** [fastai/fastai2#442]
## Description
https://github.com/fastai/fastai2/blob/a784012254cd52abede0c4c1a111940d1cce7478/docs#L1

Changes from [latest commits ](https://github.com/fastai/fastai2/commit/6801f91e2eab992c02d4405ec478cdc3181e12b1) are causing issues

`nbdev_build_lib` is calling [write_tmpls](https://github.com/fastai/nbdev/blob/master/nbdev/export2html.py#L500) but these files have been reorganized / the latest commits seem to remove the docs dir entirely

## Steps to Reproduce
1. clone repo and set up repo per `contributions` in Readme
2. `nbdev_build_lib`or `make test`

**Comment by muellerzr** [comment]
Yes, you need to clone the `fastai_docs` repo inside of your `fastai2` repo. It sym-links
