### ISSUE TITLE
AttributeError: type object 'Tensor' has no attribute 'as_subclass'

### ISSUE THREAD

**Issue by xettrisomeman** [fastai/fastai2#444]
i am having trouble using fastaiv2 , the problem is in line 240 of torch_core.py file
_
_
if not hasattr(torch,'as_subclass'):
    setattr(torch, 'as_subclass', torch.Tensor.as_subclass)

**Comment by davanstrien** [comment]
Do you have PyTorch 1.6 installed? ```torch.Tensor.as_subclass``` is introdudced in 1.6 (https://github.com/pytorch/pytorch/releases).   The latest fastai2 requires Pytroch requires 1.6 see [forum post](https://forums.fast.ai/t/major-new-changes-and-features/40742/14?u=danielvs).

**Comment by xettrisomeman** [comment]
> 
> 
> Do you have PyTorch 1.6 installed? `torch.Tensor.as_subclass` is introduced in 1.6 (https://github.com/pytorch/pytorch/releases). The latest fastai2 requires Pytroch requires 1.6 see [forum post](https://forums.fast.ai/t/major-new-changes-and-features/40742/14?u=danielvs).

Oh thanks worked ! didnot know that !
