### ISSUE TITLE
RuntimeError: imag is not implemented for tensors with non-complex dtypes.

### ISSUE THREAD

**Issue by tkrsh** [fastai/fastai2#446]
Unable to import:  from fastai2.vision.all import *
Logs:

---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-11-97b9dd603d64> in <module>
----> 1 from fastai2.vision.all import *

~/.local/lib/python3.8/site-packages/fastai2/vision/all.py in <module>
----> 1 from ..basics import *
      2 from ..callback.all import *
      3 from .augment import *
      4 from .core import *
      5 from .data import *

~/.local/lib/python3.8/site-packages/fastai2/basics.py in <module>
----> 1 from .data.all import *
      2 from .optimizer import *
      3 from .callback.core import *
      4 from .learner import *
      5 from .metrics import *

~/.local/lib/python3.8/site-packages/fastai2/data/all.py in <module>
----> 1 from ..torch_basics import *
      2 from .core import *
      3 from .load import *
      4 from .external import *
      5 from .transforms import *

~/.local/lib/python3.8/site-packages/fastai2/torch_basics.py in <module>
      2 from .imports import *
      3 from .torch_imports import *
----> 4 from .torch_core import *
      5 from .layers import *

~/.local/lib/python3.8/site-packages/fastai2/torch_core.py in <module>
    284             setattr(TensorBase, fn, get_f(fn))
    285 
--> 286 _patch_tb()
    287 
    288 # Cell

~/.local/lib/python3.8/site-packages/fastai2/torch_core.py in _patch_tb()
    280     for fn in dir(t):
    281         if fn in skips: continue
--> 282         f = getattr(t, fn)
    283         if isinstance(f, (MethodWrapperType, BuiltinFunctionType, BuiltinMethodType, MethodType, FunctionType)):
    284             setattr(TensorBase, fn, get_f(fn))

RuntimeError: imag is not implemented for tensors with non-complex dtypes.

**Comment by muellerzr** [comment]
Are you using PyTorch 1.6?

**Comment by tkrsh** [comment]
Yes

**Comment by muellerzr** [comment]
I cannot reproduce this error on my system. What platform or OS are you using? How are you installing fastai2?

**Comment by tkrsh** [comment]
I used pip install , Ubuntu 20.04 , pip 20.2, I reinstalled with pip and the error went away sorry I might be on a previous version
