### ISSUE TITLE
Can't nbdev_build_lib, File not found error

### ISSUE THREAD

**Issue by richarddwang** [fastai/fastai2#453]
Please confirm you have the latest versions of fastai, fastcore, fastscript, and nbdev prior to reporting a bug (delete one): YES (editable install for fastai, nbdev, fastcore)

**Describe the bug**
`~/fastai2 % nbdev_build_lib`
```
Traceback (most recent call last):
  File "/home/yisiang/miniconda3/envs/pr/bin/nbdev_build_lib", line 33, in <module>
    sys.exit(load_entry_point('nbdev', 'console_scripts', 'nbdev_build_lib')())
  File "/home/yisiang/miniconda3/envs/pr/lib/python3.7/site-packages/fastscript/core.py", line 76, in _f
    func(**args.__dict__)
  File "/home/yisiang/nbdev/nbdev/cli.py", line 138, in nbdev_build_lib
    write_tmpls()
  File "/home/yisiang/nbdev/nbdev/export2html.py", line 500, in write_tmpls
    write_tmpl(config_tmpl, 'user lib_name title copyright description', cfg, cfg.doc_path/'_config.yml')
  File "/home/yisiang/nbdev/nbdev/export2html.py", line 494, in write_tmpl
    dest.write_text(outp)
  File "/home/yisiang/miniconda3/envs/pr/lib/python3.7/pathlib.py", line 1235, in write_text
    with self.open(mode='w', encoding=encoding, errors=errors) as f:
  File "/home/yisiang/miniconda3/envs/pr/lib/python3.7/pathlib.py", line 1203, in open
    opener=self._opener)
  File "/home/yisiang/miniconda3/envs/pr/lib/python3.7/pathlib.py", line 1058, in _opener
    return self._accessor.open(self, flags, mode)
FileNotFoundError: [Errno 2] No such file or directory: '/home/yisiang/fastai2/docs/_config.yml'

```

**Comment by muellerzr** [comment]
Yes, you need to git clone the fastai_docs repo inside your fastai2 repo. They’re sym-linked

**Comment by hamelsmu** [comment]
@jph00 perhaps [submodules](https://github.blog/2016-02-01-working-with-submodules/) could be a potential solution to this problem?

**Comment by richarddwang** [comment]
Thanks for the comments. @muellerzr 

It seems that the answer now is to clone `fastai_dev`, so
```
|
|--- fastai2
|--- fast_dev
```
and then ...
```
~/fastai2 % rm docs # originally it link to ../fast_docs/docs, but there is no docs in fast_docs
~/fastai2 % ln -s ../fastai_dev/docs docs
```

**Comment by richarddwang** [comment]
Hi @jph00 @hamelsmu 

I think it is a good chance for us to think how to make even newbie contributor be able to make a pr smoothly.
To be specific :
1. How to integrate dependency packages (nbdev, fastcore, fastscript, fast_dev?), so we can do one clone and one editable install, don't need to be worried about other things.?
-  some dependency's version is different from fastai using now. (such as cli didn't use latest nbdev https://github.com/fastai/nbdev/issues/189)
-  There is other thing I need to clone (such as this issue)
2. Code by code .md to show how one can make his/her first pr. Follow every instruction by copy paste the code. (I would like to help on this, but it seems that there will be changes on how we can be ready to make a pr)

**Comment by muellerzr** [comment]
@richarddwang that doesn't sound right. It should be: https://github.com/fastai/fastai-docs not dev. 

So the file structure is:

* `fastai2` 
* `fastai-docs`

(I also updated the comment, it should be same *directory* as `fastai2`)

**Comment by richarddwang** [comment]
@muellerzr , I know where is the problem.
You may mean https://github.com/bhollan/fastai_docs
But I mean https://github.com/hamelsmu/fastai_docs
And both is forked from https://github.com/fastai/fastai_dev
So refer docs to fastai_dev/docs should be the right way ?

**Comment by richarddwang** [comment]
@muellerzr  Oh, so is `fastai-docs`, I copy  and search `fastai_docs` from your comment and two results actually appear haha. Thanks for the help !

**Comment by jph00** [comment]
@hamelsmu ah yes of course - submodules is a much better idea! I've changed it to a submodule now :)
