### ISSUE TITLE
Special inputs/outputs

### ISSUE THREAD

**Issue by lvaleriu** [fastai/fastai2#46]
Would it be possible to implement/show an example/tutorial of how to implement a 4 channel image input/multiple inputs (image + image, image + text) for tasks like (image segmentation/classification)? I know that some of these tasks will eventually be implemented by the community at some point (6 months after the release of a stable version), like it happened for the fastai v1. But it will boost fastai adoption if some guide to do this would be present from the beginning (personally i always fallback to keras functional api when i have to manage special inputs, etc. And I always regret what I loose when doing that).

So, would that be possible? I'm willing to contribute if you share some direction (i understand that you are probably ver busy).

Thank you!

**Comment by sgugger** [comment]
There is a tutorial that shows how to use the middle-tier APIs to generate inputs for a siamese network in [this notebook](https://github.com/fastai/fastai2/blob/master/nbs/10_tutorial.pets.ipynb) which has multiple inputs.

Closing this issue as we use the [forum](https://forums.fast.ai/) for feature requests, issues are for known bugs only.
