### ISSUE TITLE
Re-added `lang` to default tokenizer?

### ISSUE THREAD

**Issue by morganmcg1** [fastai/fastai2#467]
Previously when using Tokenizer.from_df for Irish text, I could set `lang="ga"`, which would then get passed on to SpacyTokenizer. The ability to pass a language argument seems to have been removed in the latest version of fastai2

*I'm happy to add a PR if it suits*

**Link to forum discussion.**
https://forums.fast.ai/t/fastai-v2-text/53529/397

**Is your feature request related to a problem? Please describe.**
Just noticed that WordTokenizer now calls SpacyTokenizer as the default tokenizer and passing lang to the Spacy Tokenizer is now no longer possible, meaning I cannot use Spacy's Irish (`"ga"`) model for tokenization

**Describe the solution you'd like**
Can we reinstate the ability to pass `lang` to the default tokenizer, or add a kwargs argument to the init of WordTokenizer which then can be passed to SpacyTokenizer?

Or is there a new approach I should be taking when dealing with the default tokenizer and non-english text?

**Comment by jph00** [comment]
The new approach is to simply pass an instantiated tokenizer.
