### ISSUE TITLE
error when calling TextDataBunch.from_file()

### ISSUE THREAD

**Issue by radekosmulski** [fastai/fastai2#49]
When I call `TextDataBunch.from_file(...)` I get the following error:

![image](https://user-images.githubusercontent.com/2444926/72448298-0cb5b800-37b7-11ea-81e3-976843ccf47f.png)

**Comment by sgugger** [comment]
This looks like old code, are you sure you're on master?

**Comment by radekosmulski** [comment]
Could have sworn I pulled, sorry about this.

Now pulled I think and getting this error:

![image](https://user-images.githubusercontent.com/2444926/72537408-659b5400-387c-11ea-8f58-ad263a80fe44.png)

(BTW I am not using this functionality, pieced what I need together using lower level API, just stumbled across this issue and thought I'd give you a heads up)

**Comment by sgugger** [comment]
Thanks, looks like a Path is missing somewhere, will fix.
