### ISSUE TITLE
Not able to clone fastai-docs in my clone repo.

### ISSUE THREAD

**Issue by KushajveerSingh** [fastai/fastai2#512]
### Steps to reproduce:
1. Forked fastai2 in github.
2. Ran `git clone --recurse-submodules git@github.com:KushajveerSingh/fastai2.git`, to clone the fork on my local machine.

### Error
```
Submodule 'docs' (git@github.com:KushajveerSingh/fastai-docs.git) registered for path 'docs'
Cloning into '/home/kushaj/Desktop/Github/temp/fastai2/docs'...
ERROR: Repository not found.
fatal: Could not read from remote repository.
```

### Possible solution
```
[submodule "docs"]
	path = docs
	url = https://github.com/fastai/fastai-docs
	branch = master
```

**Comment by richarddwang** [comment]
Hi @KushajveerSingh.
I think you may have the same issue with me. ([I ask in the forum](https://forums.fast.ai/t/fastai-v2-chat/53518/1318?u=richard-wang))
In this [reply](https://forums.fast.ai/t/fastai-v2-chat/53518/1319?u=richard-wang), Jeremy has confirmed my guess that when we fork `fastai2`, we should also fork `fastai-docs`

**Comment by KushajveerSingh** [comment]
@richarddwang That is because a relative path is used. If we use the full path then we do no not need to fork fastai-docs.

**Comment by richarddwang** [comment]
Oh you are right. It did use relative path now.
Hope we can solve this issue asap. ☺️

**Comment by richarddwang** [comment]
@jph00 Does closing this issue mean that absolute path didn't solve the problem (need to fork aso`fastai-dcs`) ?

**Comment by jph00** [comment]
Sorry I didn't know that u still had a problem. See the readme for information on cloning both directories if you are using a fork
