### ISSUE TITLE
Have the ability to add our own type_tfms on test_dl

### ISSUE THREAD

**Issue by muellerzr** [fastai/fastai2#522]
**Is your feature request related to a problem? Please describe.**
When you build a new `test_dl`, if your data comes in an input *not* formatted like in training, it can cause headaches. IE my data may come in as images in folders but if instead they're linked to a DataFrame in my deployment platform, worming them around into a `DataLoader` involves overriding the original dataset's type transforms

**Describe the solution you'd like**
The ability to pass in a dictionary of type transforms (or something along the lines that makes sense to override any of our transforms available), with the first being the index you want to override (such as the file and label, etc)

**Describe alternatives you've considered**
Overriding the actual transforms like below:

```python
p = Pipeline([ColReader('fname'), PILImage.create])
dls.valid_ds.tls[0].tfms = p
dls.valid_ds.tls[0].types.insert(0, pd.Series)
```
(this is just a dummy example taken from the PETs notebook). 

The other issue needed to be taken into account is if our datatypes change. IE in the above example, fastai wasn't expecting a `DataFrame`, as originally it wasn't. So if we try to pass in our series we need to adjust the `types`

**Comment by muellerzr** [comment]
This issue (and workaround) is discussed more in-detail here: 

https://muellerzr.github.io/fastblog/2020/08/10/testdl.html

**Comment by jph00** [comment]
Let's leave this until after release. Please remind me if I forget though!

**Comment by muellerzr** [comment]
Sounds good Jeremy!
