### ISSUE TITLE
We might be able to "not" also fork `fastai-docs`

### ISSUE THREAD

**Issue by richarddwang** [fastai/fastai2#526]
As pointed in #512 by @KushajveerSingh . 
We should use absolute path for `fastai-docs` in `.gitmodules`, so we need to only fork `fastai2`.
```
[submodule "docs"]
	path = docs
	url = https://github.com/fastai/fastai-docs
	branch = master
```

This is also confirmed by the answers to my question on stackoverflow.
[How to set .gitmodules so that contributors don't have to fork also submodule?](https://stackoverflow.com/questions/63371273/how-to-set-gitmodules-so-that-contributors-dont-have-to-fork-also-submodule)

It should be worth trying it.

**Comment by jph00** [comment]
That then forces https mode, but some folks (like me!) want to use ssh.
