### ISSUE TITLE
Don't turn layernorm into fp16

### ISSUE THREAD

**Issue by richarddwang** [fastai/fastai2#533]
Currently we don't turn batch norm into fp16 when using mixed precision.
https://github.com/fastai/fastai2/blob/8d798c881c1eda564bdf92079bdfe43b43525767/fastai2/fp16_utils.py#L61-L71

Seems that for the same reason we will also don't want layernorm be turned into fp16. 
![image](https://user-images.githubusercontent.com/17963619/90308680-f7069d80-df13-11ea-8135-553abe666629.png)

But if I read the code correctly, we turn layernorm into fp16 when using `to_fp16`.
I tried to fix it, but I don't know how to make a fp32 layernom consume fp16 inputs and output in fp16. Could you please fix it ?

Thanks in advance.

**Comment by jph00** [comment]
Probably best of using `to_native_fp16` to handle this for now. If you figure out a solution, feel free to send in a PR.

**Comment by richarddwang** [comment]
Got it, thanks !
