### ISSUE TITLE
Validation set contains unseen category as target

### ISSUE THREAD

**Issue by Ch4s3r** [fastai/fastai2#534]
Hello,

I noticed that on current master (https://github.com/fastai/fastai2/commit/12c99b11dd97b21c2fea81437b3648d7f03f70fc) there is no check if the validation set contains an unseen category which is not in the vocabulary in the target label. In fastai v1 you would get a warning that this sample in the validation set will be discarded and in v2 you get a `NaN` value in the target label which causes problems later on when calling `fit`.

Example error message: `IndexError: Target 3 is out of bounds.`

Code to reproduce the bug:
```python
from fastai2.tabular.all import *
import pandas as pd

items = [
    [1, 1.0, 'a'],
    [2, 2.0, 'b'],
    [3, 3.0, 'c'],
    [1, 1.0, 'a'],
    [2, 2.0, 'b'],
    [4, 4.0, 'z'],
]

df = pd.DataFrame(items, columns =['number', 'float', 'char'])
df

dep_var = 'char'
cont_names, cat_names = cont_cat_split(
    df=df,
    max_card=20,
    dep_var=dep_var
)

dls = TabularDataLoaders.from_df(
    df=df,
    procs=[FillMissing, Categorify, Normalize],
    cat_names=cat_names,
    cont_names=cont_names,
    y_names=dep_var,
    valid_idx=[4,5],
    bs=64
)

dls.valid.show_batch()
learn = tabular_learner(dls)
learn.fit_one_cycle(1)
```

The warning you usually get in v1: 
```
UserWarning: You are labelling your items with CategoryList.
Your valid set contained the following unknown labels, the corresponding items have been discarded.
z
if getattr(ds, 'warn', False): warn(ds.warn)
```

**Comment by jph00** [comment]
This is, at most, a missing feature, not a bug. We'll consider adding it after v2 is released.
