### ISSUE TITLE
Distributed Training not working after the latest commits

### ISSUE THREAD

**Issue by hussam789** [fastai/fastai2#57]
Hey,
After pulling the latest commit, it appears that Distributed Training stopped working.
we are getting this error: 
```Expected object of backend CUDA but got backend CPU for argument #2 'target' in call to _thnn_nll_loss_forward```

we checked the device type of `self.pred` on after_pred() and it appears that the `self.pred` is on the `cpu` and not on `cuda`

the latest commit that distributed training worked is around January 13'th.
maybe it's related to this commit: https://github.com/fastai/fastai2/commit/2c947668a6defeced761ce37b69be27504d72e2a

**Comment by sgugger** [comment]
Could you give the code that fails (particularly the data creation process)? Thanks.

**Comment by sgugger** [comment]
Should be fixed by #85, please reopen with a reproducible example if the issue persists.
