### ISSUE TITLE
loading pretrained xresnet50 fails silently

### ISSUE THREAD

**Issue by jaidmin** [fastai/fastai2#58]
when trying to initialize xresnet50 with pretrained=True, no error appears but performance is terrible.

The reason is that there were some renamings ("convs" -> "convpath", "idconv" -> "idpath" etc...) so the keys in the state dicts dont match anymore.
Because strict=False in the `_xresnet()` function, no error is thrown. 

I fixed the names and uploaded the updated state_dict [here](https://drive.google.com/file/d/16yriire9hvZ8bNcY137HazdTSILNNlzm/view?usp=sharing)
This version does not include the optimizer state but I don't think that's important.

**Comment by sgugger** [comment]
No pretrained models for XResnet are fully ready yet, so this is expected. You should stick with torchvision pretrained models for now. There will be xresnets available but we are waiting for the API to be fully stable before retraining them. Closing the issue as this is on our TODO list :)
