### ISSUE TITLE
pip install issue on Nvidia Jetson Nano (arm)

### ISSUE THREAD

**Issue by hongcheng79** [fastai/fastai2#59]
Bumped into the following issue when install fastai2 on Nvidia Jetson Nano which is on arm

Collecting fastprogress>=0.1.22
  Downloading fastprogress-0.2.2-py3-none-any.whl (12 kB)
ERROR: Could not find a version that satisfies the requirement torch<1.4.0,>=1.2.0 (from fastai2) (from versions: 0.1.2, 0.1.2.post1, 0.1.2.post2)
ERROR: No matching distribution found for torch<1.4.0,>=1.2.0 (from fastai2)

**Comment by sgugger** [comment]
This means there is no pytorch distribution available to you, so you should raise the issue on their github.
