### ISSUE TITLE
Unet odd sized image bug

### ISSUE THREAD

**Issue by lgvaz** [fastai/fastai2#6]
When trying to use U-net with odd sized images this error is thrown:
```python
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-25-325776f19633> in <module>
      1 timg = test_pipe('tests/stata.jpg').cuda()
----> 2 pred = TensorImage(learn.model(timg)).cpu()

~/anaconda3/envs/dl2/lib/python3.7/site-packages/torch/nn/modules/module.py in __call__(self, *input, **kwargs)
    539             result = self._slow_forward(*input, **kwargs)
    540         else:
--> 541             result = self.forward(*input, **kwargs)
    542         for hook in self._forward_hooks.values():
    543             hook_result = hook(self, input, result)

~/forks/fastai2/fastai2/layers.py in forward(self, x)
    386         for l in self.layers:
    387             res.orig = x
--> 388             nres = l(res)
    389             # We have to remove res.orig to avoid hanging refs and therefore memory leaks
    390             res.orig = None

~/anaconda3/envs/dl2/lib/python3.7/site-packages/torch/nn/modules/module.py in __call__(self, *input, **kwargs)
    539             result = self._slow_forward(*input, **kwargs)
    540         else:
--> 541             result = self.forward(*input, **kwargs)
    542         for hook in self._forward_hooks.values():
    543             hook_result = hook(self, input, result)

~/forks/fastai2/fastai2/layers.py in forward(self, x)
    401     "Merge a shortcut with the result of the module by adding them or concatenating them if `dense=True`."
    402     def __init__(self, dense:bool=False): self.dense=dense
--> 403     def forward(self, x): return torch.cat([x,x.orig], dim=1) if self.dense else (x+x.orig)
    404 
    405 #Cell

RuntimeError: invalid argument 0: Sizes of tensors must match except in dimension 1. Got 679 and 680 in dimension 2 at /opt/conda/conda-bld/pytorch_1573049306803/work/aten/src/THC/generic/THCTensorMath.cu:71
```
And checking the shapes this is what we have:
```
ipdb> x.shape
torch.Size([1, 64, 680, 1024])
ipdb> x.orig.shape
torch.Size([1, 3, 679, 1024])
```

So what I'm guessing here is that the padding on the conv layer of the network is increasing the img dimensions by 1, when the image get reconstructed by the decoder it always get rounded up to the next even number.

A solution would be to add asymmetrical padding to all the network when the image is odd, but I imagine that would be really messy really fast. Another solution would be to always pad (or resize) the image at the beginning of the network to make sure it's always even.

I would like to work on this issue and some input on what would be the best strategy would be very helpful =)

**Comment by sgugger** [comment]
The unet is the same as in v1 and only accepts sizes that are multiple of 32 (it's not just odd that is the problem). Not sure it's fixable, it comes from the upsampling path that multiplies the size by 2 at each step.

**Comment by lgvaz** [comment]
Ow, I see... Should this be added to `DynamicUnet` and `unet_learner` documentation?

Would a transform that resizes images to the closest multiple of 32 helpful? Currently it's a pain to do inference with a U-net, because I don't want my images to be resized to a fixed number.

**Comment by sgugger** [comment]
Yes it should be documented unless fixed. In v1, there was a default that put the size to a multiple of 32 by default, not sure it's in v2.

**Comment by lgvaz** [comment]
I'll check that and possibly submit a PR.

Thanks :)
