### ISSUE TITLE
Issue with the learn.predict(Imagepath)

### ISSUE THREAD

**Issue by DragonPG** [fastai/fastai2#67]
learn = torch.load(path/'export.pkl')
pred_class,pred_idx,outputs = learn.predict(path/'ClassA'/'WhatsApp Image 2020-02-01 at 08.58.27.jpeg')

The error occurring is 
learn = torch.load(path/'export.pkl')
Could not do one pass in your dataloader, there is something wrong in it
IndexError                                Traceback (most recent call last)
<ipython-input-24-dedbbc9cff09> in <module>()
      1 learn = torch.load(path/'export.pkl')
----> 2 pred_class,pred_idx,outputs = learn.predict(path/'Harshita'/'WhatsApp Image 2020-02-01 at 08.58.27.jpeg')

11 frames
/usr/local/lib/python3.6/dist-packages/fastcore/foundation.py in _get(self, i)
    318 
    319     def _get(self, i):
--> 320         if is_indexer(i) or isinstance(i,slice): return getattr(self.items,'iloc',self.items)[i]
    321         i = mask2idxs(i)
    322         return (self.items.iloc[list(i)] if hasattr(self.items,'iloc')

**Comment by sgugger** [comment]
It was a pretty bad regression, thanks for flagging it!
