### ISSUE TITLE
U-net fails to properly build

### ISSUE THREAD

**Issue by lgvaz** [fastai/fastai2#7]
I was occasionally facing the following bug when feeding forward my model (e.g. while in`lr_find`):
```python
/usr/local/lib/python3.6/dist-packages/fastai2/layers.py in forward(self, x)
    401     "Merge a shortcut with the result of the module by adding them or concatenating them if `dense=True`."
    402     def __init__(self, dense:bool=False): self.dense=dense
--> 403     def forward(self, x): return torch.cat([x,x.orig], dim=1) if self.dense else (x+x.orig)
    404 
    405 #Cell

RuntimeError: invalid argument 0: Sizes of tensors must match except in dimension 1. Got 256 and 640 in dimension 2
```
I decided to investigate and traced back the error to the following (which can be find under `unet_learner`):
```python
    try:    size = dbunch.train_ds[0][0].size
    except: size = dbunch.one_batch()[0].shape[-2:]
```

What happens is that I'm applying a resize to my when creating by databunch, like so:
```python
dbch = dblock.databunch(path, bs=bs, item_tfms=[Resize(sz)]...
```
But ` dbunch.train_ds[0][0].size` get's the original size of the image, not the transformed one, and this causes the error. (If instead `dbunch.one_batch()[0].shape[-2:]` executes everthing works correctly).

I decided to post this as a bug instead of a PR because the `try/except` must be there for a reason. For me only having the except case fixed the issue, but that might cause some unexpected damage.

**Comment by sgugger** [comment]
Good catch. The try except is copied from v1 and we should definitely use the later now, since the resize is done in the DataLoader.
