### ISSUE TITLE
New Pillow version (7.0.0) breaks torchvision (ImportError: cannot import name 'PILLOW_VERSION' from 'PIL')

### ISSUE THREAD

**Issue by IamGianluca** [fastai/fastai2#71]
There was a change introduced in `pillow==7.0.0` that is conflicting with `torchvision`. The breaking change is documented in the [pillow project's changelog](https://pillow.readthedocs.io/en/stable/releasenotes/7.0.0.html#pillow-version-constant). The issue it creates with various other libraries that depends on `pillow` can be found [in a GitHub Issue in the `torchvision` repo](https://github.com/pytorch/vision/issues/1712) and also [in a GitHub Issue in the `pillow` repo](https://github.com/python-pillow/Pillow/issues/4130).

Package managers like `poetry` or `pipenv` relies on the upstream projects to define which versions of the dependencies they are compatible with. In the `environment.yml` we currently don't set any particular limit to which version of `pillow` we can install, which means that the package manager will try to install the most recent one.

The best way I've found to prevent the problem is to downgrade `pillow` to the most recent version before 7.0.0. This works in my local development environment, but I think it would be great if we could specify it also in the main project so that we don't have to do it manually every time.

**Comment by sgugger** [comment]
Yes we are aware of this issue. torchvision fixed it on their end, so there is no need to downgrade pillow.
