### ISSUE TITLE
Callbacks that have "run" set to False will never run

### ISSUE THREAD

**Issue by borisdayma** [fastai/fastai2#77]
If we use a callback that has `self.run` set to `False`, they will never run in the future when starting a new loop.

**Example:**
```python
learn = cnn_learner(…, cbs=WandbCallback(log_preds=False))
learn.fit(1)  # callback runs

# any of the 2 lines below prevent the cb to run in the next "fit" loop
lean.show_results()
learn.lr_finder()

learn.fit(1)  # callback does not run
```

The callbacks use `self.run` to decide if they run or not and are typically set back to True at `after_fit`. However this does not execute with certain methods such as `show_results` and `lr_finder`.

**Proposed solution:**
`begin_fit` should always execute even if `self.run==False` to reevaluate `self.run`

**Comment by sgugger** [comment]
Interesting bug!, Thanks a lot for flagging this. Yes, all cbs.run should be reset to True at each fit, basically. Will fix tomorrow morning.

**Comment by borisdayma** [comment]
No worry there's no hurry. I know you guys are busy right now so I try to fix the bugs myself but I'm still having some difficulty.
