### ISSUE TITLE
ImportError: cannot import name 'Optional'

### ISSUE THREAD

**Issue by JonathanSum** [fastai/fastai2#89]
https://colab.research.google.com/drive/1JS3zoP_TCl3kmogQWYwM0tO2vBIrMaR9
I can not run it after downgrading to pytorch 1.0.1 with fastai 1.0.51

**Comment by sgugger** [comment]
This is the repository for fastai v2, not fastai v1.

**Comment by sgugger** [comment]
I tried to reproduce your notebook to get the error and fix it, but it does not appear for me.

**Comment by JonathanSum** [comment]
Sorry, I posted it on the wrong repo.

**Comment by 157239n** [comment]
Did you ended up fixing it? I'm having the same problem too

**Comment by xunan1994** [comment]
i have saved the problem.
my way is taht i install the pytorch==1.4.0

**Comment by xunan1994** [comment]
see https://github.com/pytorch/hub/issues/82
