### ISSUE TITLE
Type dispatch doesn't seem to work on custom transform

### ISSUE THREAD

**Issue by txus** [fastai/fastai2#90]
My custom transform is not running, and I suspect it's because somehow the type dispatch is ignoring it. I've put together a minimal example to reproduce (on latest master).

```python
from fastai2.basics import *
from fastai2.vision.all import *

def add_noise(img: TensorImageBW):
  print('adding noise')
  return img + torch.randn_like(img) / 4

source = untar_data(URLs.MNIST_SAMPLE)
items = get_image_files(source)

pipe = Pipeline([PILImageBW.create, ToTensor, IntToFloatTensor, add_noise])
x = pipe(items[0])
print(type(x))
```

This prints `fastai2.torch_core.TensorImageBW`, whereas it should print `adding noise` and then `fastai2.torch_core.TensorImageBW`. 

Any pointers on whether this is expected behavior or not would be welcome --I'd love to contribute a patch if it is indeed a bug. Love the library :) Thank you all for the hard work!

**Comment by sgugger** [comment]
Typedispatch is only supported if you subclass Transform and write `encodes`. It does not look for type annotations on regular functions. See the examples in the [documentation](http://fastcore.fast.ai/transform#Defining-a-Transform) for more information.

**Comment by txus** [comment]
@sgugger I rewrote the example as you mentioned, but the same behavior happens:

```python
from fastai2.basics import *
from fastai2.vision.all import *

class AddNoise(Transform):
  def encodes(img: TensorImageBW):
    print('adding noise')
    return img + torch.randn_like(img) / 4

source = untar_data(URLs.MNIST_SAMPLE)
items = get_image_files(source)

pipe = Pipeline([PILImageBW.create, ToTensor, IntToFloatTensor, AddNoise])
x = pipe(items[0])
type(x)
```

What do you think could be happening?

**Comment by hoftherose** [comment]
Not sure if this is a feature in the pipeline object, but if you print the pipe AddNoise is brought up to being the second transformation.  that ToTensor and IntToFloatTensor should be the last. I have a feeling this is a feature because most attempts to make a work around would either break or have the same result.

If this were a bug then at least it give a better idea of where it could be, otherwise you can work around by declaring FakeToTensor and FakeIntToFloatTensor Transforms which should look like this:

    class FakeToTensor(Transform):
        def encodes(self, o): return ToTensor()(o)

    class FakeIntToFloatTensor(Transform):
        def encodes(self, o): return IntToFloatTensor()(o)

Already tested it and works alright. (quick last note, remember to add self to encodes, that will also give an error)

**Comment by sgugger** [comment]
Ah ah, thanks for chipping in! I know what's happening now.

It's not a bug, the pipeline is printed with the transforms in order, so you can debug the order they are applied. It looks like your custom transform should have a higher order! You can double check with ToTensor.order, but I think it has an order of 5 or 10, so you need to set that attribute higher in `AddNoise` to make sure it runs at the right place, then you can double check by just printing your Pipeline.

**Comment by hoftherose** [comment]
Yup, that solved it, ToTensor had order at 5 but IntToFloatTensor has it at 10 so setting AddNoise to 11 did the trick without the Fake Transforms. Didn't quite understand what order did untill now, thanks for the comment!

**Comment by txus** [comment]
Thank you so much @sgugger and @hoftherose! I wasn't aware of the order at all, my mistake :)
