### ISSUE TITLE
Support int16 images

### ISSUE THREAD

**Issue by rbavery** [fastai/fastai2#91]
I was looking at the docs and noted that the Image classes all seemed to relate to using PIL (which does not support multichannel int16 or float images). I'd like to suggest that this library handle multi-channel images with int16 type. This is an issue across higher level frameworks (see https://github.com/facebookresearch/detectron2/issues/698) and makes it harder for users that work with imagery that has to be in int16 data type. For example, most satellite imagery comes in either int16 or as a float type and satellite imagery is increasingly being used with the methods available in fastaiv2.

**Comment by sgugger** [comment]
You can define your own image types that handles this in fastai v2 (see the medical module for instance). Adding support ourselves is not a priority at the moment, but you can see on the [forum](https://forums.fast.ai/) if others have already begun implementing such types already and share your code.
